export interface NameData {
  id: string;
  hebrew: string;
  transliteration: string;
  english: string;
  meaning: string;
  gender: 'male' | 'female' | 'neutral';
  nameType: 'english' | 'hebrew';
}

export const NAMES: NameData[] = [
  // English Female Names (from CSV)
  { id: '1', hebrew: 'מרים', transliteration: 'Mary', english: 'Mary', meaning: 'Of the sea', gender: 'female', nameType: 'english' },
  { id: '2', hebrew: 'אליזבט', transliteration: 'Elizabeth', english: 'Elizabeth', meaning: 'Oath of God', gender: 'female', nameType: 'english' },
  { id: '3', hebrew: 'פטריציה', transliteration: 'Patricia', english: 'Patricia', meaning: 'Noble', gender: 'female', nameType: 'english' },
  { id: '4', hebrew: 'לינדה', transliteration: 'Linda', english: 'Linda', meaning: 'Beautiful', gender: 'female', nameType: 'english' },
  { id: '5', hebrew: 'שרה', transliteration: 'Sarah', english: 'Sarah', meaning: 'Princess', gender: 'female', nameType: 'english' },
  { id: '6', hebrew: 'ג\'ניפר', transliteration: 'Jennifer', english: 'Jennifer', meaning: 'Fair one', gender: 'female', nameType: 'english' },
  { id: '7', hebrew: 'בברה', transliteration: 'Barbara', english: 'Barbara', meaning: 'Stranger', gender: 'female', nameType: 'english' },
  { id: '8', hebrew: 'דבורה', transliteration: 'Deborah', english: 'Deborah', meaning: 'Bee', gender: 'female', nameType: 'english' },
  { id: '9', hebrew: 'מרגרט', transliteration: 'Margaret', english: 'Margaret', meaning: 'Pearl', gender: 'female', nameType: 'english' },
  { id: '10', hebrew: 'קתרין', transliteration: 'Katherine', english: 'Katherine', meaning: 'Pure', gender: 'female', nameType: 'english' },
  { id: '11', hebrew: 'דורותי', transliteration: 'Dorothy', english: 'Dorothy', meaning: 'Gift of God', gender: 'female', nameType: 'english' },
  { id: '12', hebrew: 'סוזן', transliteration: 'Susan', english: 'Susan', meaning: 'Graceful lily', gender: 'female', nameType: 'english' },
  { id: '13', hebrew: 'ג\'סיקה', transliteration: 'Jessica', english: 'Jessica', meaning: 'Wealthy', gender: 'female', nameType: 'english' },
  { id: '14', hebrew: 'מישל', transliteration: 'Michelle', english: 'Michelle', meaning: 'Who is like God', gender: 'female', nameType: 'english' },
  { id: '15', hebrew: 'בטי', transliteration: 'Betty', english: 'Betty', meaning: 'Devoted to God', gender: 'female', nameType: 'english' },
  { id: '16', hebrew: 'הלן', transliteration: 'Helen', english: 'Helen', meaning: 'Shining light', gender: 'female', nameType: 'english' },
  { id: '17', hebrew: 'אנה', transliteration: 'Anna', english: 'Anna', meaning: 'Grace', gender: 'female', nameType: 'english' },
  { id: '18', hebrew: 'ננסי', transliteration: 'Nancy', english: 'Nancy', meaning: 'Graceful', gender: 'female', nameType: 'english' },
  { id: '19', hebrew: 'קרן', transliteration: 'Karen', english: 'Karen', meaning: 'Pure', gender: 'female', nameType: 'english' },
  { id: '20', hebrew: 'ליסה', transliteration: 'Lisa', english: 'Lisa', meaning: 'Devoted to God', gender: 'female', nameType: 'english' },
  { id: '21', hebrew: 'קרול', transliteration: 'Carol', english: 'Carol', meaning: 'Free', gender: 'female', nameType: 'english' },
  { id: '22', hebrew: 'אמילי', transliteration: 'Emily', english: 'Emily', meaning: 'Industrious', gender: 'female', nameType: 'english' },
  { id: '23', hebrew: 'קימברלי', transliteration: 'Kimberly', english: 'Kimberly', meaning: 'From a wood of royal forest', gender: 'female', nameType: 'english' },
  { id: '24', hebrew: 'סנדרה', transliteration: 'Sandra', english: 'Sandra', meaning: 'Defender of mankind', gender: 'female', nameType: 'english' },
  { id: '25', hebrew: 'אשלי', transliteration: 'Ashley', english: 'Ashley', meaning: 'Ash tree meadow', gender: 'female', nameType: 'english' },
  { id: '26', hebrew: 'לורה', transliteration: 'Laura', english: 'Laura', meaning: 'Laurel', gender: 'female', nameType: 'english' },
  { id: '27', hebrew: 'רות', transliteration: 'Ruth', english: 'Ruth', meaning: 'Friend, companion', gender: 'female', nameType: 'english' },
  { id: '28', hebrew: 'דונה', transliteration: 'Donna', english: 'Donna', meaning: 'Lady', gender: 'female', nameType: 'english' },
  { id: '29', hebrew: 'תרזה', transliteration: 'Teresa', english: 'Teresa', meaning: 'Harvester', gender: 'female', nameType: 'english' },
  { id: '30', hebrew: 'סטפני', transliteration: 'Stephanie', english: 'Stephanie', meaning: 'Crown', gender: 'female', nameType: 'english' },
  { id: '31', hebrew: 'אן', transliteration: 'Ann', english: 'Ann', meaning: 'Grace', gender: 'female', nameType: 'english' },
  { id: '32', hebrew: 'אמנדה', transliteration: 'Amanda', english: 'Amanda', meaning: 'Worthy of love', gender: 'female', nameType: 'english' },
  { id: '33', hebrew: 'מליסה', transliteration: 'Melissa', english: 'Melissa', meaning: 'Honey bee', gender: 'female', nameType: 'english' },
  { id: '34', hebrew: 'רבקה', transliteration: 'Rebecca', english: 'Rebecca', meaning: 'To bind', gender: 'female', nameType: 'english' },
  { id: '35', hebrew: 'אמה', transliteration: 'Emma', english: 'Emma', meaning: 'Whole', gender: 'female', nameType: 'english' },
  { id: '36', hebrew: 'שרון', transliteration: 'Sharon', english: 'Sharon', meaning: 'Plain', gender: 'female', nameType: 'english' },
  { id: '37', hebrew: 'קתלין', transliteration: 'Kathleen', english: 'Kathleen', meaning: 'Pure', gender: 'female', nameType: 'english' },
  { id: '38', hebrew: 'סינתיה', transliteration: 'Cynthia', english: 'Cynthia', meaning: 'Moon goddess', gender: 'female', nameType: 'english' },
  { id: '39', hebrew: 'איימי', transliteration: 'Amy', english: 'Amy', meaning: 'Beloved', gender: 'female', nameType: 'english' },
  { id: '40', hebrew: 'שרלי', transliteration: 'Shirley', english: 'Shirley', meaning: 'From the white meadow', gender: 'female', nameType: 'english' },
  { id: '41', hebrew: 'אנג\'לה', transliteration: 'Angela', english: 'Angela', meaning: 'Angel, messenger', gender: 'female', nameType: 'english' },
  { id: '42', hebrew: 'כריסטין', transliteration: 'Christine', english: 'Christine', meaning: 'Follower of Christ', gender: 'female', nameType: 'english' },
  { id: '43', hebrew: 'כריסטינה', transliteration: 'Christina', english: 'Christina', meaning: 'Follower of Christ', gender: 'female', nameType: 'english' },
  { id: '44', hebrew: 'קתרין', transliteration: 'Catherine', english: 'Catherine', meaning: 'Pure', gender: 'female', nameType: 'english' },
  { id: '45', hebrew: 'רחל', transliteration: 'Rachel', english: 'Rachel', meaning: 'Ewe', gender: 'female', nameType: 'english' },
  { id: '46', hebrew: 'וירג\'יניה', transliteration: 'Virginia', english: 'Virginia', meaning: 'Pure', gender: 'female', nameType: 'english' },
  { id: '47', hebrew: 'קלי', transliteration: 'Kelly', english: 'Kelly', meaning: 'Bright-headed', gender: 'female', nameType: 'english' },
  { id: '48', hebrew: 'ג\'ין', transliteration: 'Jean', english: 'Jean', meaning: 'God is gracious', gender: 'female', nameType: 'english' },
  { id: '49', hebrew: 'פרנסס', transliteration: 'Frances', english: 'Frances', meaning: 'Free', gender: 'female', nameType: 'english' },
  { id: '50', hebrew: 'אווליין', transliteration: 'Evelyn', english: 'Evelyn', meaning: 'Desired', gender: 'female', nameType: 'english' },
  { id: '51', hebrew: 'דיאן', transliteration: 'Diane', english: 'Diane', meaning: 'Divine', gender: 'female', nameType: 'english' },
  { id: '52', hebrew: 'ברנדה', transliteration: 'Brenda', english: 'Brenda', meaning: 'Beacon', gender: 'female', nameType: 'english' },
  { id: '53', hebrew: 'אליס', transliteration: 'Alice', english: 'Alice', meaning: 'Noble', gender: 'female', nameType: 'english' },
  { id: '54', hebrew: 'ניקול', transliteration: 'Nicole', english: 'Nicole', meaning: 'Victory of the people', gender: 'female', nameType: 'english' },
  { id: '55', hebrew: 'פמלה', transliteration: 'Pamela', english: 'Pamela', meaning: 'All honey', gender: 'female', nameType: 'english' },
  { id: '56', hebrew: 'סמנתה', transliteration: 'Samantha', english: 'Samantha', meaning: 'Listener', gender: 'female', nameType: 'english' },
  { id: '57', hebrew: 'סופיה', transliteration: 'Sophia', english: 'Sophia', meaning: 'Wisdom', gender: 'female', nameType: 'english' },
  { id: '58', hebrew: 'לורי', transliteration: 'Lori', english: 'Lori', meaning: 'Laurel', gender: 'female', nameType: 'english' },
  { id: '59', hebrew: 'קרולין', transliteration: 'Carolyn', english: 'Carolyn', meaning: 'Free', gender: 'female', nameType: 'english' },
  { id: '60', hebrew: 'מריה', transliteration: 'Maria', english: 'Maria', meaning: 'Of the sea', gender: 'female', nameType: 'english' },
  { id: '61', hebrew: 'ג\'אנט', transliteration: 'Janet', english: 'Janet', meaning: 'God is gracious', gender: 'female', nameType: 'english' },
  { id: '62', hebrew: 'מרתה', transliteration: 'Martha', english: 'Martha', meaning: 'Lady', gender: 'female', nameType: 'english' },
  { id: '63', hebrew: 'מארי', transliteration: 'Marie', english: 'Marie', meaning: 'Of the sea', gender: 'female', nameType: 'english' },
  { id: '64', hebrew: 'אוליביה', transliteration: 'Olivia', english: 'Olivia', meaning: 'Olive tree', gender: 'female', nameType: 'english' },
  { id: '65', hebrew: 'קתי', transliteration: 'Kathy', english: 'Kathy', meaning: 'Pure', gender: 'female', nameType: 'english' },
  { id: '66', hebrew: 'הדר', transliteration: 'Heather', english: 'Heather', meaning: 'Flowering plant', gender: 'female', nameType: 'english' },
  { id: '67', hebrew: 'גרייס', transliteration: 'Grace', english: 'Grace', meaning: 'Elegance', gender: 'female', nameType: 'english' },
  { id: '68', hebrew: 'שריל', transliteration: 'Cheryl', english: 'Cheryl', meaning: 'Beloved', gender: 'female', nameType: 'english' },
  { id: '69', hebrew: 'וויקטוריה', transliteration: 'Victoria', english: 'Victoria', meaning: 'Victory', gender: 'female', nameType: 'english' },
  { id: '70', hebrew: 'ג\'ולי', transliteration: 'Julie', english: 'Julie', meaning: 'Youthful', gender: 'female', nameType: 'english' },
  { id: '71', hebrew: 'חנה', transliteration: 'Hannah', english: 'Hannah', meaning: 'Grace', gender: 'female', nameType: 'english' },
  { id: '72', hebrew: 'ג\'ויס', transliteration: 'Joyce', english: 'Joyce', meaning: 'Joyful', gender: 'female', nameType: 'english' },
  { id: '73', hebrew: 'רוז', transliteration: 'Rose', english: 'Rose', meaning: 'Flower', gender: 'female', nameType: 'english' },
  { id: '74', hebrew: 'ג\'קלין', transliteration: 'Jacqueline', english: 'Jacqueline', meaning: 'Supplanter', gender: 'female', nameType: 'english' },
  { id: '75', hebrew: 'ליליאן', transliteration: 'Lillian', english: 'Lillian', meaning: 'Lily', gender: 'female', nameType: 'english' },
  { id: '76', hebrew: 'לורן', transliteration: 'Lauren', english: 'Lauren', meaning: 'Laurel', gender: 'female', nameType: 'english' },
  { id: '77', hebrew: 'אליסון', transliteration: 'Allison', english: 'Allison', meaning: 'Noble', gender: 'female', nameType: 'english' },
  { id: '78', hebrew: 'ג\'ואן', transliteration: 'Joan', english: 'Joan', meaning: 'God is gracious', gender: 'female', nameType: 'english' },
  { id: '79', hebrew: 'שרי', transliteration: 'Sherry', english: 'Sherry', meaning: 'Beloved', gender: 'female', nameType: 'english' },
  { id: '80', hebrew: 'ג\'וליה', transliteration: 'Julia', english: 'Julia', meaning: 'Youthful', gender: 'female', nameType: 'english' },
  { id: '81', hebrew: 'דוריס', transliteration: 'Doris', english: 'Doris', meaning: 'Of the sea', gender: 'female', nameType: 'english' },
  { id: '82', hebrew: 'ג\'אניס', transliteration: 'Janice', english: 'Janice', meaning: 'God is gracious', gender: 'female', nameType: 'english' },
  { id: '83', hebrew: 'יהודית', transliteration: 'Judith', english: 'Judith', meaning: 'Woman of Judea', gender: 'female', nameType: 'english' },
  { id: '84', hebrew: 'קריסטל', transliteration: 'Crystal', english: 'Crystal', meaning: 'Clear', gender: 'female', nameType: 'english' },
  { id: '85', hebrew: 'מילדרד', transliteration: 'Mildred', english: 'Mildred', meaning: 'Gentle strength', gender: 'female', nameType: 'english' },
  { id: '86', hebrew: 'אנדריאה', transliteration: 'Andrea', english: 'Andrea', meaning: 'Strong', gender: 'female', nameType: 'english' },
  { id: '87', hebrew: 'מיגן', transliteration: 'Megan', english: 'Megan', meaning: 'Pearl', gender: 'female', nameType: 'english' },
  { id: '88', hebrew: 'קארי', transliteration: 'Carrie', english: 'Carrie', meaning: 'Free', gender: 'female', nameType: 'english' },
  { id: '89', hebrew: 'שרלוט', transliteration: 'Charlotte', english: 'Charlotte', meaning: 'Free woman', gender: 'female', nameType: 'english' },
  { id: '90', hebrew: 'טרייסי', transliteration: 'Tracy', english: 'Tracy', meaning: 'Harvester', gender: 'female', nameType: 'english' },
  { id: '91', hebrew: 'גלוריה', transliteration: 'Gloria', english: 'Gloria', meaning: 'Glorious', gender: 'female', nameType: 'english' },
  { id: '92', hebrew: 'מדיסון', transliteration: 'Madison', english: 'Madison', meaning: 'Son of Maud', gender: 'female', nameType: 'english' },
  { id: '93', hebrew: 'לילי', transliteration: 'Lily', english: 'Lily', meaning: 'Flower', gender: 'female', nameType: 'english' },
  { id: '94', hebrew: 'ג\'יין', transliteration: 'Jane', english: 'Jane', meaning: 'God is gracious', gender: 'female', nameType: 'english' },
  { id: '95', hebrew: 'תמי', transliteration: 'Tammy', english: 'Tammy', meaning: 'Palm tree', gender: 'female', nameType: 'english' },
  { id: '96', hebrew: 'אביגיל', transliteration: 'Abigail', english: 'Abigail', meaning: 'Father\'s joy', gender: 'female', nameType: 'english' },
  { id: '97', hebrew: 'איזבלה', transliteration: 'Isabella', english: 'Isabella', meaning: 'Devoted to God', gender: 'female', nameType: 'english' },
  { id: '98', hebrew: 'נטלי', transliteration: 'Natalie', english: 'Natalie', meaning: 'Christmas Day', gender: 'female', nameType: 'english' },
  { id: '99', hebrew: 'ג\'ודי', transliteration: 'Judy', english: 'Judy', meaning: 'Woman of Judea', gender: 'female', nameType: 'english' },
  { id: '100', hebrew: 'בברלי', transliteration: 'Beverly', english: 'Beverly', meaning: 'Beaver stream', gender: 'female', nameType: 'english' },
  
  // English Male Names (from CSV)
  { id: '101', hebrew: 'ג\'יימס', transliteration: 'James', english: 'James', meaning: 'Supplanter', gender: 'male', nameType: 'english' },
  { id: '102', hebrew: 'ג\'ון', transliteration: 'John', english: 'John', meaning: 'God is gracious', gender: 'male', nameType: 'english' },
  { id: '103', hebrew: 'רוברט', transliteration: 'Robert', english: 'Robert', meaning: 'Bright fame', gender: 'male', nameType: 'english' },
  { id: '104', hebrew: 'מיכאל', transliteration: 'Michael', english: 'Michael', meaning: 'Who is like God', gender: 'male', nameType: 'english' },
  { id: '105', hebrew: 'וויליאם', transliteration: 'William', english: 'William', meaning: 'Resolute protector', gender: 'male', nameType: 'english' },
  { id: '106', hebrew: 'דוד', transliteration: 'David', english: 'David', meaning: 'Beloved', gender: 'male', nameType: 'english' },
  { id: '107', hebrew: 'ריצ\'רד', transliteration: 'Richard', english: 'Richard', meaning: 'Brave ruler', gender: 'male', nameType: 'english' },
  { id: '108', hebrew: 'יוסף', transliteration: 'Joseph', english: 'Joseph', meaning: 'God increases', gender: 'male', nameType: 'english' },
  { id: '109', hebrew: 'תומס', transliteration: 'Thomas', english: 'Thomas', meaning: 'Twin', gender: 'male', nameType: 'english' },
  { id: '110', hebrew: 'צ\'ארלס', transliteration: 'Charles', english: 'Charles', meaning: 'Free man', gender: 'male', nameType: 'english' },
  { id: '111', hebrew: 'כריסטופר', transliteration: 'Christopher', english: 'Christopher', meaning: 'Bearer of Christ', gender: 'male', nameType: 'english' },
  { id: '112', hebrew: 'מתיו', transliteration: 'Matthew', english: 'Matthew', meaning: 'Gift of God', gender: 'male', nameType: 'english' },
  { id: '113', hebrew: 'מארק', transliteration: 'Mark', english: 'Mark', meaning: 'Dedicated to Mars', gender: 'male', nameType: 'english' },
  { id: '114', hebrew: 'אנתוני', transliteration: 'Anthony', english: 'Anthony', meaning: 'Priceless', gender: 'male', nameType: 'english' },
  { id: '115', hebrew: 'דניאל', transliteration: 'Daniel', english: 'Daniel', meaning: 'God is judge', gender: 'male', nameType: 'english' },
  { id: '116', hebrew: 'דונלד', transliteration: 'Donald', english: 'Donald', meaning: 'World leader', gender: 'male', nameType: 'english' },
  { id: '117', hebrew: 'קנת', transliteration: 'Kenneth', english: 'Kenneth', meaning: 'Handsome', gender: 'male', nameType: 'english' },
  { id: '118', hebrew: 'סטיבן', transliteration: 'Steven', english: 'Steven', meaning: 'Crown', gender: 'male', nameType: 'english' },
  { id: '119', hebrew: 'פול', transliteration: 'Paul', english: 'Paul', meaning: 'Small', gender: 'male', nameType: 'english' },
  { id: '120', hebrew: 'אנדרו', transliteration: 'Andrew', english: 'Andrew', meaning: 'Strong and manly', gender: 'male', nameType: 'english' },
  { id: '121', hebrew: 'יהושע', transliteration: 'Joshua', english: 'Joshua', meaning: 'God is salvation', gender: 'male', nameType: 'english' },
  { id: '122', hebrew: 'בנימין', transliteration: 'Benjamin', english: 'Benjamin', meaning: 'Son of the right hand', gender: 'male', nameType: 'english' },
  { id: '123', hebrew: 'יעקב', transliteration: 'Jacob', english: 'Jacob', meaning: 'Supplanter', gender: 'male', nameType: 'english' },
  { id: '124', hebrew: 'אדוארד', transliteration: 'Edward', english: 'Edward', meaning: 'Wealthy guardian', gender: 'male', nameType: 'english' },
  { id: '125', hebrew: 'רייאן', transliteration: 'Ryan', english: 'Ryan', meaning: 'Little king', gender: 'male', nameType: 'english' },
  { id: '126', hebrew: 'גרי', transliteration: 'Gary', english: 'Gary', meaning: 'Spear', gender: 'male', nameType: 'english' },
  { id: '127', hebrew: 'ניקולס', transliteration: 'Nicholas', english: 'Nicholas', meaning: 'Victory of the people', gender: 'male', nameType: 'english' },
  { id: '128', hebrew: 'אריק', transliteration: 'Eric', english: 'Eric', meaning: 'Eternal ruler', gender: 'male', nameType: 'english' },
  { id: '129', hebrew: 'יוני', transliteration: 'Jonathan', english: 'Jonathan', meaning: 'God gave', gender: 'male', nameType: 'english' },
  { id: '130', hebrew: 'סטיפן', transliteration: 'Stephen', english: 'Stephen', meaning: 'Crown', gender: 'male', nameType: 'english' },
  { id: '131', hebrew: 'לארי', transliteration: 'Larry', english: 'Larry', meaning: 'Laurel', gender: 'male', nameType: 'english' },
  { id: '132', hebrew: 'ג\'סטין', transliteration: 'Justin', english: 'Justin', meaning: 'Just', gender: 'male', nameType: 'english' },
  { id: '133', hebrew: 'סקוט', transliteration: 'Scott', english: 'Scott', meaning: 'From Scotland', gender: 'male', nameType: 'english' },
  { id: '134', hebrew: 'בראנדון', transliteration: 'Brandon', english: 'Brandon', meaning: 'Fiery hill', gender: 'male', nameType: 'english' },
  { id: '135', hebrew: 'סמואל', transliteration: 'Samuel', english: 'Samuel', meaning: 'God has heard', gender: 'male', nameType: 'english' },
  { id: '136', hebrew: 'ריימונד', transliteration: 'Raymond', english: 'Raymond', meaning: 'Wise protector', gender: 'male', nameType: 'english' },
  { id: '137', hebrew: 'פטריק', transliteration: 'Patrick', english: 'Patrick', meaning: 'Noble', gender: 'male', nameType: 'english' },
  { id: '138', hebrew: 'ג\'ק', transliteration: 'Jack', english: 'Jack', meaning: 'God is gracious', gender: 'male', nameType: 'english' },
  { id: '139', hebrew: 'דניס', transliteration: 'Dennis', english: 'Dennis', meaning: 'Dedicated to Dionysus', gender: 'male', nameType: 'english' },
  { id: '140', hebrew: 'ג\'רי', transliteration: 'Jerry', english: 'Jerry', meaning: 'Holy name', gender: 'male', nameType: 'english' },
  { id: '141', hebrew: 'טיילר', transliteration: 'Tyler', english: 'Tyler', meaning: 'Tile maker', gender: 'male', nameType: 'english' },
  { id: '142', hebrew: 'אהרון', transliteration: 'Aaron', english: 'Aaron', meaning: 'Mountain of strength', gender: 'male', nameType: 'english' },
  { id: '143', hebrew: 'הוסה', transliteration: 'Jose', english: 'Jose', meaning: 'God increases', gender: 'male', nameType: 'english' },
  { id: '144', hebrew: 'אדם', transliteration: 'Adam', english: 'Adam', meaning: 'Man', gender: 'male', nameType: 'english' },
  { id: '145', hebrew: 'הנרי', transliteration: 'Henry', english: 'Henry', meaning: 'House ruler', gender: 'male', nameType: 'english' },
  { id: '146', hebrew: 'דגלס', transliteration: 'Douglas', english: 'Douglas', meaning: 'Dark river', gender: 'male', nameType: 'english' },
  { id: '147', hebrew: 'פטר', transliteration: 'Peter', english: 'Peter', meaning: 'Stone', gender: 'male', nameType: 'english' },
  { id: '148', hebrew: 'זכריה', transliteration: 'Zachary', english: 'Zachary', meaning: 'God remembers', gender: 'male', nameType: 'english' },
  
  // Biblical Names (Hebrew and English)
  { id: '149', hebrew: 'אברהם', transliteration: 'Abraham', english: 'Abraham', meaning: 'Father of multitude', gender: 'male', nameType: 'hebrew' },
  { id: '150', hebrew: 'יצחק', transliteration: 'Isaac', english: 'Isaac', meaning: 'He will laugh', gender: 'male', nameType: 'hebrew' },
  { id: '151', hebrew: 'יעקב', transliteration: 'Jacob', english: 'Jacob', meaning: 'Supplanter', gender: 'male', nameType: 'hebrew' },
  { id: '152', hebrew: 'יהודה', transliteration: 'Judah', english: 'Judah', meaning: 'Praised', gender: 'male', nameType: 'hebrew' },
  { id: '153', hebrew: 'יוסף', transliteration: 'Joseph', english: 'Joseph', meaning: 'God increases', gender: 'male', nameType: 'hebrew' },
  { id: '154', hebrew: 'משה', transliteration: 'Moses', english: 'Moses', meaning: 'Drawn out', gender: 'male', nameType: 'hebrew' },
  { id: '155', hebrew: 'דוד', transliteration: 'David', english: 'David', meaning: 'Beloved', gender: 'male', nameType: 'hebrew' },
  { id: '156', hebrew: 'שלמה', transliteration: 'Solomon', english: 'Solomon', meaning: 'Peaceful', gender: 'male', nameType: 'hebrew' },
  { id: '157', hebrew: 'אליהו', transliteration: 'Elijah', english: 'Elijah', meaning: 'My God is Yah', gender: 'male', nameType: 'hebrew' },
  { id: '158', hebrew: 'אלישע', transliteration: 'Elisha', english: 'Elisha', meaning: 'God is salvation', gender: 'male', nameType: 'hebrew' },
  { id: '159', hebrew: 'יחזקאל', transliteration: 'Ezekiel', english: 'Ezekiel', meaning: 'God strengthens', gender: 'male', nameType: 'hebrew' },
  { id: '160', hebrew: 'ירמיה', transliteration: 'Jeremiah', english: 'Jeremiah', meaning: 'God will exalt', gender: 'male', nameType: 'hebrew' },
  { id: '161', hebrew: 'ישעיה', transliteration: 'Isaiah', english: 'Isaiah', meaning: 'God is salvation', gender: 'male', nameType: 'hebrew' },
  { id: '162', hebrew: 'שמואל', transliteration: 'Samuel', english: 'Samuel', meaning: 'God has heard', gender: 'male', nameType: 'hebrew' },
  { id: '163', hebrew: 'בנימין', transliteration: 'Benjamin', english: 'Benjamin', meaning: 'Son of the right hand', gender: 'male', nameType: 'hebrew' },
  { id: '164', hebrew: 'רובן', transliteration: 'Reuben', english: 'Reuben', meaning: 'Behold a son', gender: 'male', nameType: 'hebrew' },
  { id: '165', hebrew: 'שמעון', transliteration: 'Simeon', english: 'Simeon', meaning: 'He has heard', gender: 'male', nameType: 'hebrew' },
  { id: '166', hebrew: 'לוי', transliteration: 'Levi', english: 'Levi', meaning: 'Joined', gender: 'male', nameType: 'hebrew' },
  { id: '167', hebrew: 'יששכר', transliteration: 'Issachar', english: 'Issachar', meaning: 'He has hired', gender: 'male', nameType: 'hebrew' },
  { id: '168', hebrew: 'זבולון', transliteration: 'Zebulun', english: 'Zebulun', meaning: 'Dwelling place', gender: 'male', nameType: 'hebrew' },
  { id: '169', hebrew: 'דן', transliteration: 'Dan', english: 'Dan', meaning: 'Judge', gender: 'male', nameType: 'hebrew' },
  { id: '170', hebrew: 'נפתלי', transliteration: 'Naphtali', english: 'Naphtali', meaning: 'My struggle', gender: 'male', nameType: 'hebrew' },
  { id: '171', hebrew: 'גד', transliteration: 'Gad', english: 'Gad', meaning: 'Fortune', gender: 'male', nameType: 'hebrew' },
  { id: '172', hebrew: 'אשר', transliteration: 'Asher', english: 'Asher', meaning: 'Happy', gender: 'male', nameType: 'hebrew' },
  { id: '173', hebrew: 'אפרים', transliteration: 'Ephraim', english: 'Ephraim', meaning: 'Fruitful', gender: 'male', nameType: 'hebrew' },
  { id: '174', hebrew: 'מנשה', transliteration: 'Manasseh', english: 'Manasseh', meaning: 'Making forget', gender: 'male', nameType: 'hebrew' },
  { id: '175', hebrew: 'מלאכי', transliteration: 'Malachi', english: 'Malachi', meaning: 'My messenger', gender: 'male', nameType: 'hebrew' },
  { id: '176', hebrew: 'הושע', transliteration: 'Hosea', english: 'Hosea', meaning: 'Salvation', gender: 'male', nameType: 'hebrew' },
  { id: '177', hebrew: 'יוחנן', transliteration: 'John', english: 'John', meaning: 'God is gracious', gender: 'male', nameType: 'hebrew' },
  { id: '178', hebrew: 'נחום', transliteration: 'Nahum', english: 'Nahum', meaning: 'Comfort', gender: 'male', nameType: 'hebrew' },
  { id: '179', hebrew: 'חביקוק', transliteration: 'Habakkuk', english: 'Habakkuk', meaning: 'Embrace', gender: 'male', nameType: 'hebrew' },
  { id: '180', hebrew: 'צפניה', transliteration: 'Zephaniah', english: 'Zephaniah', meaning: 'Hidden by God', gender: 'male', nameType: 'hebrew' },
  { id: '181', hebrew: 'חגי', transliteration: 'Haggai', english: 'Haggai', meaning: 'My festival', gender: 'male', nameType: 'hebrew' },
  { id: '182', hebrew: 'זכריה', transliteration: 'Zechariah', english: 'Zechariah', meaning: 'God remembers', gender: 'male', nameType: 'hebrew' },
  { id: '183', hebrew: 'שרה', transliteration: 'Sarah', english: 'Sarah', meaning: 'Princess', gender: 'female', nameType: 'hebrew' },
  { id: '184', hebrew: 'רבקה', transliteration: 'Rebecca', english: 'Rebecca', meaning: 'To tie', gender: 'female', nameType: 'hebrew' },
  { id: '185', hebrew: 'לאה', transliteration: 'Leah', english: 'Leah', meaning: 'Weary', gender: 'female', nameType: 'hebrew' },
  { id: '186', hebrew: 'רחל', transliteration: 'Rachel', english: 'Rachel', meaning: 'Ewe', gender: 'female', nameType: 'hebrew' },
  { id: '187', hebrew: 'מרים', transliteration: 'Miriam', english: 'Miriam', meaning: 'Bitter sea', gender: 'female', nameType: 'hebrew' },
  { id: '188', hebrew: 'דבורה', transliteration: 'Deborah', english: 'Deborah', meaning: 'Bee', gender: 'female', nameType: 'hebrew' },
  { id: '189', hebrew: 'רות', transliteration: 'Ruth', english: 'Ruth', meaning: 'Friend', gender: 'female', nameType: 'hebrew' },
  { id: '190', hebrew: 'אסתר', transliteration: 'Esther', english: 'Esther', meaning: 'Star', gender: 'female', nameType: 'hebrew' },
  { id: '191', hebrew: 'חנה', transliteration: 'Hannah', english: 'Hannah', meaning: 'Grace', gender: 'female', nameType: 'hebrew' },
  { id: '192', hebrew: 'יהודית', transliteration: 'Judith', english: 'Judith', meaning: 'Woman of Judea', gender: 'female', nameType: 'hebrew' },
  { id: '193', hebrew: 'תמר', transliteration: 'Tamar', english: 'Tamar', meaning: 'Date Palm', gender: 'female', nameType: 'hebrew' },
  { id: '194', hebrew: 'דינה', transliteration: 'Dinah', english: 'Dinah', meaning: 'Judged', gender: 'female', nameType: 'hebrew' },
  { id: '195', hebrew: 'בתשבע', transliteration: 'Bathsheba', english: 'Bathsheba', meaning: 'Daughter of oath', gender: 'female', nameType: 'hebrew' },
  { id: '196', hebrew: 'מיכל', transliteration: 'Michal', english: 'Michal', meaning: 'Who is like God', gender: 'female', nameType: 'hebrew' },
  { id: '197', hebrew: 'אביגיל', transliteration: 'Abigail', english: 'Abigail', meaning: 'My father is joy', gender: 'female', nameType: 'hebrew' },
  { id: '198', hebrew: 'נעמי', transliteration: 'Naomi', english: 'Naomi', meaning: 'Pleasantness', gender: 'female', nameType: 'hebrew' },
  { id: '199', hebrew: 'עופרה', transliteration: 'Ophrah', english: 'Ophrah', meaning: 'Fawn', gender: 'female', nameType: 'hebrew' },
  { id: '200', hebrew: 'שושנה', transliteration: 'Susanna', english: 'Susanna', meaning: 'Lily', gender: 'female', nameType: 'hebrew' },
  { id: '201', hebrew: 'אלדד', transliteration: 'Eldad', english: 'Eldad', meaning: 'God loves', gender: 'male', nameType: 'hebrew' },
  { id: '202', hebrew: 'אל', transliteration: 'El', english: 'El', meaning: 'God', gender: 'neutral', nameType: 'hebrew' },
  { id: '203', hebrew: 'עומר', transliteration: 'Omer', english: 'Omer', meaning: 'Sheaf of wheat', gender: 'male', nameType: 'hebrew' },
  { id: '204', hebrew: 'אביתר', transliteration: 'Abiathar', english: 'Abiathar', meaning: 'Father is great', gender: 'male', nameType: 'hebrew' },
  { id: '205', hebrew: 'צדוק', transliteration: 'Zadok', english: 'Zadok', meaning: 'Righteous', gender: 'male', nameType: 'hebrew' },
  { id: '206', hebrew: 'אבשלום', transliteration: 'Absalom', english: 'Absalom', meaning: 'Father of peace', gender: 'male', nameType: 'hebrew' },
  { id: '207', hebrew: 'יהוידע', transliteration: 'Jehoiada', english: 'Jehoiada', meaning: 'God knows', gender: 'male', nameType: 'hebrew' },
  { id: '208', hebrew: 'יהונתן', transliteration: 'Jonathan', english: 'Jonathan', meaning: 'God gave', gender: 'male', nameType: 'hebrew' },
  { id: '209', hebrew: 'אבינדב', transliteration: 'Abinadab', english: 'Abinadab', meaning: 'Father of willingness', gender: 'male', nameType: 'hebrew' },
  { id: '210', hebrew: 'עמרי', transliteration: 'Omri', english: 'Omri', meaning: 'Sheaf of God', gender: 'male', nameType: 'hebrew' },
  { id: '211', hebrew: 'אאלייאה', transliteration: 'Aaliyah', english: 'Aaliyah', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '212', hebrew: 'אבבי', transliteration: 'Abby', english: 'Abby', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '213', hebrew: 'אדא', transliteration: 'Ada', english: 'Ada', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '214', hebrew: 'אדאליננ', transliteration: 'Adalynn', english: 'Adalynn', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '215', hebrew: 'אדדיא', transliteration: 'Addie', english: 'Addie', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '216', hebrew: 'אדדישאנ', transliteration: 'Addison', english: 'Addison', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '217', hebrew: 'אדאלאידא', transliteration: 'Adelaide', english: 'Adelaide', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '218', hebrew: 'אדאלא', transliteration: 'Adele', english: 'Adele', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '219', hebrew: 'אדאלינא', transliteration: 'Adeline', english: 'Adeline', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '220', hebrew: 'אדאלינ', transliteration: 'Adelyn', english: 'Adelyn', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '221', hebrew: 'אדריאנא', transliteration: 'Adriana', english: 'Adriana', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '222', hebrew: 'אדריאננא', transliteration: 'Adrianna', english: 'Adrianna', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '223', hebrew: 'אדריאננא', transliteration: 'Adrienne', english: 'Adrienne', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '224', hebrew: 'אאנאש', transliteration: 'Agnes', english: 'Agnes', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '225', hebrew: 'אימאא', transliteration: 'Aimee', english: 'Aimee', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '226', hebrew: 'אינשלאי', transliteration: 'Ainsley', english: 'Ainsley', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '227', hebrew: 'אישהא', transliteration: 'Aisha', english: 'Aisha', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '228', hebrew: 'אלאינא', transliteration: 'Alaina', english: 'Alaina', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '229', hebrew: 'אלאנא', transliteration: 'Alana', english: 'Alana', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '230', hebrew: 'אלאננא', transliteration: 'Alanna', english: 'Alanna', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '231', hebrew: 'אלאיאה', transliteration: 'Alayah', english: 'Alayah', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '232', hebrew: 'אלאינא', transliteration: 'Alayna', english: 'Alayna', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '233', hebrew: 'אלבארתא', transliteration: 'Alberta', english: 'Alberta', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '234', hebrew: 'אלאאאנדרא', transliteration: 'Alejandra', english: 'Alejandra', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '235', hebrew: 'אלאששאנדרא', transliteration: 'Alessandra', english: 'Alessandra', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '236', hebrew: 'אלאאא', transliteration: 'Alexa', english: 'Alexa', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '237', hebrew: 'אלאאאנדרא', transliteration: 'Alexandra', english: 'Alexandra', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '238', hebrew: 'אלאאאנדריא', transliteration: 'Alexandria', english: 'Alexandria', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '239', hebrew: 'אלאאיא', transliteration: 'Alexia', english: 'Alexia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '240', hebrew: 'אלאאיש', transliteration: 'Alexis', english: 'Alexis', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '241', hebrew: 'אליאיא', transliteration: 'Alicia', english: 'Alicia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '242', hebrew: 'אלינא', transliteration: 'Alina', english: 'Alina', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '243', hebrew: 'אלישהא', transliteration: 'Alisha', english: 'Alisha', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '244', hebrew: 'אליאיא', transliteration: 'Alivia', english: 'Alivia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '245', hebrew: 'אלייאה', transliteration: 'Aliyah', english: 'Aliyah', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '246', hebrew: 'אלליא', transliteration: 'Allie', english: 'Allie', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '247', hebrew: 'אלמא', transliteration: 'Alma', english: 'Alma', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '248', hebrew: 'אלאנדרא', transliteration: 'Alondra', english: 'Alondra', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '249', hebrew: 'אלישאנ', transliteration: 'Alyson', english: 'Alyson', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '250', hebrew: 'אליששא', transliteration: 'Alyssa', english: 'Alyssa', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '251', hebrew: 'אמארא', transliteration: 'Amara', english: 'Amara', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '252', hebrew: 'אמאליא', transliteration: 'Amelia', english: 'Amelia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '253', hebrew: 'אמיא', transliteration: 'Amie', english: 'Amie', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '254', hebrew: 'אמינא', transliteration: 'Amina', english: 'Amina', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '255', hebrew: 'אמירא', transliteration: 'Amira', english: 'Amira', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '256', hebrew: 'אנאבאל', transliteration: 'Anabel', english: 'Anabel', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '257', hebrew: 'אנאהי', transliteration: 'Anahi', english: 'Anahi', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '258', hebrew: 'אנאשתאשיא', transliteration: 'Anastasia', english: 'Anastasia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '259', hebrew: 'אנאאל', transliteration: 'Angel', english: 'Angel', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '260', hebrew: 'אנאאליא', transliteration: 'Angelia', english: 'Angelia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '261', hebrew: 'אנאאליאא', transliteration: 'Angelica', english: 'Angelica', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '262', hebrew: 'אנאאלינא', transliteration: 'Angelina', english: 'Angelina', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '263', hebrew: 'אנאאלינא', transliteration: 'Angeline', english: 'Angeline', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '264', hebrew: 'אנאאליאוא', transliteration: 'Angelique', english: 'Angelique', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '265', hebrew: 'אנאיא', transliteration: 'Angie', english: 'Angie', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '266', hebrew: 'אניתא', transliteration: 'Anita', english: 'Anita', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '267', hebrew: 'אננאבאללא', transliteration: 'Annabelle', english: 'Annabelle', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '268', hebrew: 'אננאתתא', transliteration: 'Annette', english: 'Annette', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '269', hebrew: 'אנניא', transliteration: 'Annie', english: 'Annie', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '270', hebrew: 'אנניאא', transliteration: 'Annika', english: 'Annika', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '271', hebrew: 'אננמאריא', transliteration: 'Annmarie', english: 'Annmarie', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '272', hebrew: 'אנתאינאתתא', transliteration: 'Antoinette', english: 'Antoinette', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '273', hebrew: 'אנתאניא', transliteration: 'Antonia', english: 'Antonia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '274', hebrew: 'אניא', transliteration: 'Anya', english: 'Anya', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '275', hebrew: 'אאריל', transliteration: 'April', english: 'April', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '276', hebrew: 'אראבאללא', transliteration: 'Arabella', english: 'Arabella', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '277', hebrew: 'אראאאלי', transliteration: 'Araceli', english: 'Araceli', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '278', hebrew: 'אריא', transliteration: 'Aria', english: 'Aria', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '279', hebrew: 'אריאנא', transliteration: 'Ariana', english: 'Ariana', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '280', hebrew: 'אריאללא', transliteration: 'Ariella', english: 'Ariella', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '281', hebrew: 'אריאללא', transliteration: 'Arielle', english: 'Arielle', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '282', hebrew: 'ארלאנא', transliteration: 'Arlene', english: 'Arlene', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '283', hebrew: 'ארלינא', transliteration: 'Arline', english: 'Arline', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '284', hebrew: 'אריא', transliteration: 'Arya', english: 'Arya', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '285', hebrew: 'אריאננא', transliteration: 'Aryanna', english: 'Aryanna', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '286', hebrew: 'אשהלאא', transliteration: 'Ashlee', english: 'Ashlee', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '287', hebrew: 'אשהלי', transliteration: 'Ashly', english: 'Ashly', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '288', hebrew: 'אשהלינ', transliteration: 'Ashlyn', english: 'Ashlyn', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '289', hebrew: 'אשיא', transliteration: 'Asia', english: 'Asia', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '290', hebrew: 'אשאאנ', transliteration: 'Aspen', english: 'Aspen', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '291', hebrew: 'אתהאנא', transliteration: 'Athena', english: 'Athena', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '292', hebrew: 'אובראא', transliteration: 'Aubree', english: 'Aubree', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '293', hebrew: 'אובראי', transliteration: 'Aubrey', english: 'Aubrey', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '294', hebrew: 'אודרא', transliteration: 'Audra', english: 'Audra', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '295', hebrew: 'אורארא', transliteration: 'Aurora', english: 'Aurora', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '296', hebrew: 'אותומנ', transliteration: 'Autumn', english: 'Autumn', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '297', hebrew: 'איאננא', transliteration: 'Ayanna', english: 'Ayanna', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '298', hebrew: 'אילא', transliteration: 'Ayla', english: 'Ayla', meaning: 'Precious name', gender: 'female', nameType: 'english' },
  { id: '299', hebrew: 'אאראנ', transliteration: 'Aaron', english: 'Aaron', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '300', hebrew: 'אבאל', transliteration: 'Abel', english: 'Abel', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '301', hebrew: 'אבראהאמ', transliteration: 'Abraham', english: 'Abraham', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '302', hebrew: 'אדאמ', transliteration: 'Adam', english: 'Adam', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '303', hebrew: 'אדאנ', transliteration: 'Adan', english: 'Adan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '304', hebrew: 'אדריאנ', transliteration: 'Adrian', english: 'Adrian', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '305', hebrew: 'אידאנ', transliteration: 'Aidan', english: 'Aidan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '306', hebrew: 'אידאנ', transliteration: 'Aiden', english: 'Aiden', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '307', hebrew: 'אלאנ', transliteration: 'Alan', english: 'Alan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '308', hebrew: 'אלבארת', transliteration: 'Albert', english: 'Albert', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '309', hebrew: 'אלבארתא', transliteration: 'Alberto', english: 'Alberto', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '310', hebrew: 'אלאא', transliteration: 'Alec', english: 'Alec', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '311', hebrew: 'אלאאאנדרא', transliteration: 'Alejandro', english: 'Alejandro', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '312', hebrew: 'אלאא', transliteration: 'Alex', english: 'Alex', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '313', hebrew: 'אלאאאנדאר', transliteration: 'Alexander', english: 'Alexander', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '314', hebrew: 'אלאראד', transliteration: 'Alfred', english: 'Alfred', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '315', hebrew: 'אלאראדא', transliteration: 'Alfredo', english: 'Alfredo', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '316', hebrew: 'אלתאנ', transliteration: 'Alton', english: 'Alton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '317', hebrew: 'אלאינ', transliteration: 'Alvin', english: 'Alvin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '318', hebrew: 'אמיר', transliteration: 'Amir', english: 'Amir', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '319', hebrew: 'אנדרא', transliteration: 'Andre', english: 'Andre', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '320', hebrew: 'אנדראש', transliteration: 'Andres', english: 'Andres', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '321', hebrew: 'אנדראא', transliteration: 'Andrew', english: 'Andrew', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '322', hebrew: 'אנדי', transliteration: 'Andy', english: 'Andy', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '323', hebrew: 'אנאאלא', transliteration: 'Angelo', english: 'Angelo', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '324', hebrew: 'אנתהאני', transliteration: 'Anthony', english: 'Anthony', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '325', hebrew: 'אנתאניא', transliteration: 'Antonio', english: 'Antonio', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '326', hebrew: 'אראהיא', transliteration: 'Archie', english: 'Archie', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '327', hebrew: 'ארמאנדא', transliteration: 'Armando', english: 'Armando', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '328', hebrew: 'ארנאלד', transliteration: 'Arnold', english: 'Arnold', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '329', hebrew: 'ארתהור', transliteration: 'Arthur', english: 'Arthur', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '330', hebrew: 'ארתורא', transliteration: 'Arturo', english: 'Arturo', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '331', hebrew: 'אשהאר', transliteration: 'Asher', english: 'Asher', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '332', hebrew: 'אואושת', transliteration: 'August', english: 'August', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '333', hebrew: 'אושתינ', transliteration: 'Austin', english: 'Austin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '334', hebrew: 'אאאל', transliteration: 'Axel', english: 'Axel', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '335', hebrew: 'אידאנ', transliteration: 'Ayden', english: 'Ayden', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '336', hebrew: 'באררי', transliteration: 'Barry', english: 'Barry', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '337', hebrew: 'באאו', transliteration: 'Beau', english: 'Beau', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '338', hebrew: 'באנ', transliteration: 'Ben', english: 'Ben', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '339', hebrew: 'באנאאמינ', transliteration: 'Benjamin', english: 'Benjamin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '340', hebrew: 'באננאתת', transliteration: 'Bennett', english: 'Bennett', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '341', hebrew: 'באנניא', transliteration: 'Bennie', english: 'Bennie', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '342', hebrew: 'באנתלאי', transliteration: 'Bentley', english: 'Bentley', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '343', hebrew: 'בארנארד', transliteration: 'Bernard', english: 'Bernard', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '344', hebrew: 'בילל', transliteration: 'Bill', english: 'Bill', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '345', hebrew: 'ביללי', transliteration: 'Billy', english: 'Billy', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '346', hebrew: 'בלאאא', transliteration: 'Blake', english: 'Blake', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '347', hebrew: 'באב', transliteration: 'Bob', english: 'Bob', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '348', hebrew: 'באבבי', transliteration: 'Bobby', english: 'Bobby', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '349', hebrew: 'בראד', transliteration: 'Brad', english: 'Brad', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '350', hebrew: 'בראדלאי', transliteration: 'Bradley', english: 'Bradley', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '351', hebrew: 'בראדי', transliteration: 'Brady', english: 'Brady', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '352', hebrew: 'בראנדאנ', transliteration: 'Brandon', english: 'Brandon', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '353', hebrew: 'בראאתאנ', transliteration: 'Braxton', english: 'Braxton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '354', hebrew: 'בראידאנ', transliteration: 'Brayden', english: 'Brayden', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '355', hebrew: 'בראנדאנ', transliteration: 'Brendan', english: 'Brendan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '356', hebrew: 'בראנת', transliteration: 'Brent', english: 'Brent', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '357', hebrew: 'בראתת', transliteration: 'Brett', english: 'Brett', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '358', hebrew: 'בריאנ', transliteration: 'Brian', english: 'Brian', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '359', hebrew: 'בראדי', transliteration: 'Brody', english: 'Brody', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '360', hebrew: 'בראאאש', transliteration: 'Brooks', english: 'Brooks', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '361', hebrew: 'ברואא', transliteration: 'Bruce', english: 'Bruce', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '362', hebrew: 'בריאנת', transliteration: 'Bryant', english: 'Bryant', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '363', hebrew: 'בריאא', transliteration: 'Bryce', english: 'Bryce', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '364', hebrew: 'ברישאנ', transliteration: 'Bryson', english: 'Bryson', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '365', hebrew: 'ביראנ', transliteration: 'Byron', english: 'Byron', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '366', hebrew: 'אאדא', transliteration: 'Cade', english: 'Cade', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '367', hebrew: 'אאדאנ', transliteration: 'Caden', english: 'Caden', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '368', hebrew: 'אאלאב', transliteration: 'Caleb', english: 'Caleb', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '369', hebrew: 'אאלאינ', transliteration: 'Calvin', english: 'Calvin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '370', hebrew: 'אאמדאנ', transliteration: 'Camden', english: 'Camden', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '371', hebrew: 'אאמאראנ', transliteration: 'Cameron', english: 'Cameron', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '372', hebrew: 'אארל', transliteration: 'Carl', english: 'Carl', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '373', hebrew: 'אארלאש', transliteration: 'Carlos', english: 'Carlos', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '374', hebrew: 'אארלתאנ', transliteration: 'Carlton', english: 'Carlton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '375', hebrew: 'אארשאנ', transliteration: 'Carson', english: 'Carson', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '376', hebrew: 'אארתאר', transliteration: 'Carter', english: 'Carter', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '377', hebrew: 'אאשאי', transliteration: 'Casey', english: 'Casey', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '378', hebrew: 'אאאיל', transliteration: 'Cecil', english: 'Cecil', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '379', hebrew: 'אאשאר', transliteration: 'Cesar', english: 'Cesar', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '380', hebrew: 'אהאד', transliteration: 'Chad', english: 'Chad', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '381', hebrew: 'אהאנאא', transliteration: 'Chance', english: 'Chance', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '382', hebrew: 'אהארלאש', transliteration: 'Charles', english: 'Charles', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '383', hebrew: 'אהארליא', transliteration: 'Charlie', english: 'Charlie', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '384', hebrew: 'אהאשא', transliteration: 'Chase', english: 'Chase', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '385', hebrew: 'אהאשתאר', transliteration: 'Chester', english: 'Chester', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '386', hebrew: 'אהריש', transliteration: 'Chris', english: 'Chris', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '387', hebrew: 'אהרישתיאנ', transliteration: 'Christian', english: 'Christian', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '388', hebrew: 'אהרישתאאהאר', transliteration: 'Christopher', english: 'Christopher', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '389', hebrew: 'אלאראנאא', transliteration: 'Clarence', english: 'Clarence', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '390', hebrew: 'אלארא', transliteration: 'Clark', english: 'Clark', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '391', hebrew: 'אלאודא', transliteration: 'Claude', english: 'Claude', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '392', hebrew: 'אלאיתאנ', transliteration: 'Clayton', english: 'Clayton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '393', hebrew: 'אליאאארד', transliteration: 'Clifford', english: 'Clifford', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '394', hebrew: 'אליאתאנ', transliteration: 'Clifton', english: 'Clifton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '395', hebrew: 'אלינתאנ', transliteration: 'Clinton', english: 'Clinton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '396', hebrew: 'אלידא', transliteration: 'Clyde', english: 'Clyde', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '397', hebrew: 'אאדי', transliteration: 'Cody', english: 'Cody', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '398', hebrew: 'אאלבי', transliteration: 'Colby', english: 'Colby', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '399', hebrew: 'אאלא', transliteration: 'Cole', english: 'Cole', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '400', hebrew: 'אאלינ', transliteration: 'Colin', english: 'Colin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '401', hebrew: 'אאללינ', transliteration: 'Collin', english: 'Collin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '402', hebrew: 'אאלתאנ', transliteration: 'Colton', english: 'Colton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '403', hebrew: 'אאננאר', transliteration: 'Connor', english: 'Connor', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '404', hebrew: 'אאאאאר', transliteration: 'Cooper', english: 'Cooper', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '405', hebrew: 'אארבינ', transliteration: 'Corbin', english: 'Corbin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '406', hebrew: 'אאראי', transliteration: 'Corey', english: 'Corey', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '407', hebrew: 'אארי', transliteration: 'Cory', english: 'Cory', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '408', hebrew: 'אראיא', transliteration: 'Craig', english: 'Craig', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '409', hebrew: 'ארישתיאנ', transliteration: 'Cristian', english: 'Cristian', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '410', hebrew: 'אורתיש', transliteration: 'Curtis', english: 'Curtis', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '411', hebrew: 'דאאאתא', transliteration: 'Dakota', english: 'Dakota', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '412', hebrew: 'דאלא', transliteration: 'Dale', english: 'Dale', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '413', hebrew: 'דאללאש', transliteration: 'Dallas', english: 'Dallas', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '414', hebrew: 'דאלתאנ', transliteration: 'Dalton', english: 'Dalton', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '415', hebrew: 'דאמיאנ', transliteration: 'Damian', english: 'Damian', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '416', hebrew: 'דאמאנ', transliteration: 'Damon', english: 'Damon', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '417', hebrew: 'דאנ', transliteration: 'Dan', english: 'Dan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '418', hebrew: 'דאנא', transliteration: 'Dana', english: 'Dana', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '419', hebrew: 'דאניאל', transliteration: 'Daniel', english: 'Daniel', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '420', hebrew: 'דאנני', transliteration: 'Danny', english: 'Danny', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '421', hebrew: 'דאנתא', transliteration: 'Dante', english: 'Dante', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '422', hebrew: 'דארינ', transliteration: 'Darin', english: 'Darin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '423', hebrew: 'דאריוש', transliteration: 'Darius', english: 'Darius', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '424', hebrew: 'דארראלל', transliteration: 'Darrell', english: 'Darrell', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '425', hebrew: 'דארראנ', transliteration: 'Darren', english: 'Darren', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '426', hebrew: 'דאאא', transliteration: 'Dave', english: 'Dave', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '427', hebrew: 'דאאיד', transliteration: 'David', english: 'David', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '428', hebrew: 'דאאשאנ', transliteration: 'Dawson', english: 'Dawson', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '429', hebrew: 'דאאנ', transliteration: 'Dean', english: 'Dean', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '430', hebrew: 'דאאלאנ', transliteration: 'Declan', english: 'Declan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '431', hebrew: 'דאנניש', transliteration: 'Dennis', english: 'Dennis', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '432', hebrew: 'דאראא', transliteration: 'Derek', english: 'Derek', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '433', hebrew: 'דאאינ', transliteration: 'Devin', english: 'Devin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '434', hebrew: 'דאאאנ', transliteration: 'Devon', english: 'Devon', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '435', hebrew: 'דיאאא', transliteration: 'Diego', english: 'Diego', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '436', hebrew: 'דאמיניא', transliteration: 'Dominic', english: 'Dominic', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '437', hebrew: 'דאנ', transliteration: 'Don', english: 'Don', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '438', hebrew: 'דאנאלד', transliteration: 'Donald', english: 'Donald', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '439', hebrew: 'דאנניא', transliteration: 'Donnie', english: 'Donnie', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '440', hebrew: 'דאנאאאנ', transliteration: 'Donovan', english: 'Donovan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '441', hebrew: 'דאואלאש', transliteration: 'Douglas', english: 'Douglas', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '442', hebrew: 'דראא', transliteration: 'Drew', english: 'Drew', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '443', hebrew: 'דואנא', transliteration: 'Duane', english: 'Duane', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '444', hebrew: 'דושתינ', transliteration: 'Dustin', english: 'Dustin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '445', hebrew: 'דאיאהת', transliteration: 'Dwight', english: 'Dwight', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '446', hebrew: 'דילאנ', transliteration: 'Dylan', english: 'Dylan', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '447', hebrew: 'אארל', transliteration: 'Earl', english: 'Earl', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '448', hebrew: 'אארנאשת', transliteration: 'Earnest', english: 'Earnest', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '449', hebrew: 'אד', transliteration: 'Ed', english: 'Ed', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '450', hebrew: 'אדדיא', transliteration: 'Eddie', english: 'Eddie', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '451', hebrew: 'אדאאר', transliteration: 'Edgar', english: 'Edgar', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '452', hebrew: 'אדמאנד', transliteration: 'Edmond', english: 'Edmond', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '453', hebrew: 'אדמונד', transliteration: 'Edmund', english: 'Edmund', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '454', hebrew: 'אדאארד', transliteration: 'Edward', english: 'Edward', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '455', hebrew: 'אדאינ', transliteration: 'Edwin', english: 'Edwin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '456', hebrew: 'אאראנ', transliteration: 'Efren', english: 'Efren', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '457', hebrew: 'אאבארת', transliteration: 'Egbert', english: 'Egbert', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '458', hebrew: 'אלבארת', transliteration: 'Elbert', english: 'Elbert', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '459', hebrew: 'אלביא', transliteration: 'Elbie', english: 'Elbie', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '460', hebrew: 'אלדאנ', transliteration: 'Elden', english: 'Elden', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '461', hebrew: 'אלדינ', transliteration: 'Eldin', english: 'Eldin', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '462', hebrew: 'אלדראד', transliteration: 'Eldred', english: 'Eldred', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '463', hebrew: 'אלדרידאא', transliteration: 'Eldridge', english: 'Eldridge', meaning: 'Precious name', gender: 'male', nameType: 'english' },
  { id: '464', hebrew: 'אלאאאאר', transliteration: 'Eleazar', english: 'Eleazar', meaning: 'Precious name', gender: 'male', nameType: 'english' },];
