export interface NameData {
  id: string;
  hebrew: string;
  transliteration: string;
  english: string;
  meaning: string;
  gender: 'male' | 'female' | 'neutral';
  nameType: 'english' | 'hebrew';
}

export const NAMES: NameData[] = [
  // English Names (100+)
  { id: '1', hebrew: 'אריאל', transliteration: 'Ariel', english: 'Ariel', meaning: 'Lion of God', gender: 'neutral', nameType: 'english' },
  { id: '2', hebrew: 'נועה', transliteration: 'Noa', english: 'Noa', meaning: 'Motion, Movement', gender: 'female', nameType: 'english' },
  { id: '3', hebrew: 'דוד', transliteration: 'David', english: 'David', meaning: 'Beloved', gender: 'male', nameType: 'english' },
  { id: '4', hebrew: 'שרה', transliteration: 'Sarah', english: 'Sarah', meaning: 'Princess', gender: 'female', nameType: 'english' },
  { id: '5', hebrew: 'יוסף', transliteration: 'Yosef', english: 'Joseph', meaning: 'He will add', gender: 'male', nameType: 'english' },
  { id: '6', hebrew: 'חנה', transliteration: 'Chana', english: 'Hannah', meaning: 'Grace', gender: 'female', nameType: 'english' },
  { id: '7', hebrew: 'בנימין', transliteration: 'Binyamin', english: 'Benjamin', meaning: 'Son of the right hand', gender: 'male', nameType: 'english' },
  { id: '8', hebrew: 'רחל', transliteration: 'Rachel', english: 'Rachel', meaning: 'Ewe', gender: 'female', nameType: 'english' },
  { id: '9', hebrew: 'איתן', transliteration: 'Eitan', english: 'Ethan', meaning: 'Strong, Enduring', gender: 'male', nameType: 'english' },
  { id: '10', hebrew: 'מיה', transliteration: 'Maya', english: 'Maya', meaning: 'Water', gender: 'female', nameType: 'english' },
  { id: '11', hebrew: 'אביב', transliteration: 'Aviv', english: 'Aviv', meaning: 'Spring', gender: 'neutral', nameType: 'english' },
  { id: '12', hebrew: 'תמר', transliteration: 'Tamar', english: 'Tamar', meaning: 'Date Palm', gender: 'female', nameType: 'english' },
  { id: '13', hebrew: 'עומר', transliteration: 'Omer', english: 'Omer', meaning: 'Sheaf of wheat', gender: 'male', nameType: 'english' },
  { id: '14', hebrew: 'שירה', transliteration: 'Shira', english: 'Shira', meaning: 'Song, Poetry', gender: 'female', nameType: 'english' },
  { id: '15', hebrew: 'מיכאל', transliteration: 'Michael', english: 'Michael', meaning: 'Who is like God?', gender: 'male', nameType: 'english' },
  { id: '16', hebrew: 'לאה', transliteration: 'Leah', english: 'Leah', meaning: 'Weary', gender: 'female', nameType: 'english' },
  { id: '17', hebrew: 'יצחק', transliteration: 'Yitzhak', english: 'Isaac', meaning: 'He will laugh', gender: 'male', nameType: 'english' },
  { id: '18', hebrew: 'רבקה', transliteration: 'Rivka', english: 'Rebecca', meaning: 'To tie', gender: 'female', nameType: 'english' },
  { id: '19', hebrew: 'יעקב', transliteration: 'Yaakov', english: 'Jacob', meaning: 'To follow', gender: 'male', nameType: 'english' },
  { id: '20', hebrew: 'אסתר', transliteration: 'Esther', english: 'Esther', meaning: 'Star', gender: 'female', nameType: 'english' },
  { id: '21', hebrew: 'אברהם', transliteration: 'Avraham', english: 'Abraham', meaning: 'Father of many', gender: 'male', nameType: 'english' },
  { id: '22', hebrew: 'מרים', transliteration: 'Miriam', english: 'Miriam', meaning: 'Bitter sea', gender: 'female', nameType: 'english' },
  { id: '23', hebrew: 'משה', transliteration: 'Moshe', english: 'Moses', meaning: 'Drawn from water', gender: 'male', nameType: 'english' },
  { id: '24', hebrew: 'אלי', transliteration: 'Eli', english: 'Eli', meaning: 'Ascent', gender: 'male', nameType: 'english' },
  { id: '25', hebrew: 'טליה', transliteration: 'Talia', english: 'Talia', meaning: 'Dew from God', gender: 'female', nameType: 'english' },
  { id: '26', hebrew: 'דניאל', transliteration: 'Daniel', english: 'Daniel', meaning: 'God is my judge', gender: 'male', nameType: 'english' },
  { id: '27', hebrew: 'יהודית', transliteration: 'Yehudit', english: 'Judith', meaning: 'Woman of Judea', gender: 'female', nameType: 'english' },
  { id: '28', hebrew: 'שלמה', transliteration: 'Shlomo', english: 'Solomon', meaning: 'Peaceful', gender: 'male', nameType: 'english' },
  { id: '29', hebrew: 'בתשבע', transliteration: 'Batsheva', english: 'Bathsheba', meaning: 'Daughter of oath', gender: 'female', nameType: 'english' },
  { id: '30', hebrew: 'יונה', transliteration: 'Yona', english: 'Jonah', meaning: 'Dove', gender: 'male', nameType: 'english' },
  { id: '31', hebrew: 'יהודה', transliteration: 'Yehuda', english: 'Judah', meaning: 'Praised', gender: 'male', nameType: 'english' },
  { id: '32', hebrew: 'סוזן', transliteration: 'Suzan', english: 'Susan', meaning: 'Graceful lily', gender: 'female', nameType: 'english' },
  { id: '33', hebrew: 'אפרים', transliteration: 'Ephraim', english: 'Ephraim', meaning: 'Fruitful', gender: 'male', nameType: 'english' },
  { id: '34', hebrew: 'אמנון', transliteration: 'Amnon', english: 'Amnon', meaning: 'Faithful', gender: 'male', nameType: 'english' },
  { id: '35', hebrew: 'מנשה', transliteration: 'Menashe', english: 'Manasseh', meaning: 'Making forget', gender: 'male', nameType: 'english' },
  { id: '36', hebrew: 'אסף', transliteration: 'Asaf', english: 'Asaph', meaning: 'Gatherer', gender: 'male', nameType: 'english' },
  { id: '37', hebrew: 'דבורה', transliteration: 'Devora', english: 'Deborah', meaning: 'Bee', gender: 'female', nameType: 'english' },
  { id: '38', hebrew: 'ג\'אד', transliteration: 'Gad', english: 'Gad', meaning: 'Fortune', gender: 'male', nameType: 'english' },
  { id: '39', hebrew: 'נפתלי', transliteration: 'Naftali', english: 'Naphtali', meaning: 'My struggle', gender: 'male', nameType: 'english' },
  { id: '40', hebrew: 'רוט', transliteration: 'Rut', english: 'Ruth', meaning: 'Friend, companion', gender: 'female', nameType: 'english' },
  { id: '41', hebrew: 'צפניה', transliteration: 'Tzfanya', english: 'Zephaniah', meaning: 'Hidden by God', gender: 'male', nameType: 'english' },
  { id: '42', hebrew: 'עובדיה', transliteration: 'Obadya', english: 'Obadiah', meaning: 'Servant of God', gender: 'male', nameType: 'english' },
  { id: '43', hebrew: 'מלאכי', transliteration: 'Malachi', english: 'Malachi', meaning: 'My messenger', gender: 'male', nameType: 'english' },
  { id: '44', hebrew: 'ירמיה', transliteration: 'Yirmiya', english: 'Jeremiah', meaning: 'God will exalt', gender: 'male', nameType: 'english' },
  { id: '45', hebrew: 'יחזקאל', transliteration: 'Yechezkel', english: 'Ezekiel', meaning: 'God strengthens', gender: 'male', nameType: 'english' },
  { id: '46', hebrew: 'שמואל', transliteration: 'Shmuel', english: 'Samuel', meaning: 'God has heard', gender: 'male', nameType: 'english' },
  { id: '47', hebrew: 'שאול', transliteration: 'Shaul', english: 'Saul', meaning: 'Asked for', gender: 'male', nameType: 'english' },
  { id: '48', hebrew: 'עזריה', transliteration: 'Azarya', english: 'Azariah', meaning: 'God helps', gender: 'male', nameType: 'english' },
  { id: '49', hebrew: 'חזקיה', transliteration: 'Hezekiah', english: 'Hezekiah', meaning: 'God strengthens', gender: 'male', nameType: 'english' },
  { id: '50', hebrew: 'יוסיה', transliteration: 'Yoshiyahu', english: 'Josiah', meaning: 'God supports', gender: 'male', nameType: 'english' },
  { id: '51', hebrew: 'שלום', transliteration: 'Shalom', english: 'Shalom', meaning: 'Peace', gender: 'neutral', nameType: 'english' },
  { id: '52', hebrew: 'אור', transliteration: 'Or', english: 'Or', meaning: 'Light', gender: 'neutral', nameType: 'english' },
  { id: '53', hebrew: 'אתי', transliteration: 'Adi', english: 'Adi', meaning: 'My jewel', gender: 'female', nameType: 'english' },
  { id: '54', hebrew: 'יד', transliteration: 'Yad', english: 'Yad', meaning: 'Hand', gender: 'neutral', nameType: 'english' },
  { id: '55', hebrew: 'נמרוד', transliteration: 'Nimrod', english: 'Nimrod', meaning: 'Mighty hunter', gender: 'male', nameType: 'english' },
  { id: '56', hebrew: 'בלעם', transliteration: 'Bilam', english: 'Balaam', meaning: 'Not of the people', gender: 'male', nameType: 'english' },
  { id: '57', hebrew: 'קרח', transliteration: 'Korach', english: 'Korah', meaning: 'Baldness', gender: 'male', nameType: 'english' },
  { id: '58', hebrew: 'אנוש', transliteration: 'Enosh', english: 'Enosh', meaning: 'Mortal man', gender: 'male', nameType: 'english' },
  { id: '59', hebrew: 'מתושלח', transliteration: 'Metushelach', english: 'Methuselah', meaning: 'Man of the dart', gender: 'male', nameType: 'english' },
  { id: '60', hebrew: 'נח', transliteration: 'Noach', english: 'Noah', meaning: 'Rest, comfort', gender: 'male', nameType: 'english' },
  { id: '61', hebrew: 'לוט', transliteration: 'Lot', english: 'Lot', meaning: 'Concealed', gender: 'male', nameType: 'english' },
  { id: '62', hebrew: 'יהוידע', transliteration: 'Yehoyada', english: 'Jehoiada', meaning: 'God knows', gender: 'male', nameType: 'english' },
  { id: '63', hebrew: 'יהונתן', transliteration: 'Yehonatan', english: 'Jonathan', meaning: 'God gave', gender: 'male', nameType: 'english' },
  { id: '64', hebrew: 'אבינדב', transliteration: 'Abinadav', english: 'Abinadab', meaning: 'Father of willingness', gender: 'male', nameType: 'english' },
  { id: '65', hebrew: 'עמרי', transliteration: 'Omri', english: 'Omri', meaning: 'Sheaf of God', gender: 'male', nameType: 'english' },
  { id: '66', hebrew: 'אחאב', transliteration: 'Ahav', english: 'Ahab', meaning: 'Father\'s brother', gender: 'male', nameType: 'english' },
  { id: '67', hebrew: 'יהורם', transliteration: 'Yehoram', english: 'Jehoram', meaning: 'God is exalted', gender: 'male', nameType: 'english' },
  { id: '68', hebrew: 'יהוש', transliteration: 'Yehosh', english: 'Jehoash', meaning: 'God gives', gender: 'male', nameType: 'english' },
  { id: '69', hebrew: 'יהו', transliteration: 'Yehu', english: 'Jehu', meaning: 'He is Yah', gender: 'male', nameType: 'english' },
  { id: '70', hebrew: 'יוטם', transliteration: 'Yotam', english: 'Jotham', meaning: 'God is perfect', gender: 'male', nameType: 'english' },
  { id: '71', hebrew: 'אחז', transliteration: 'Achaz', english: 'Ahaz', meaning: 'God grasps', gender: 'male', nameType: 'english' },
  { id: '72', hebrew: 'שנאצר', transliteration: 'Sennacherib', english: 'Sennacherib', meaning: 'Sin has replaced brothers', gender: 'male', nameType: 'english' },
  { id: '73', hebrew: 'נבוכדנצר', transliteration: 'Nebuchadnezzar', english: 'Nebuchadnezzar', meaning: 'Nabu protect the son', gender: 'male', nameType: 'english' },
  { id: '74', hebrew: 'בלשצר', transliteration: 'Belshatzar', english: 'Belshazzar', meaning: 'Bel protect the king', gender: 'male', nameType: 'english' },
  { id: '75', hebrew: 'מרדכי', transliteration: 'Mordechai', english: 'Mordecai', meaning: 'Follower of Marduk', gender: 'male', nameType: 'english' },
  { id: '76', hebrew: 'מנחם', transliteration: 'Menachem', english: 'Menahem', meaning: 'Comforter', gender: 'male', nameType: 'english' },
  { id: '77', hebrew: 'צדקיה', transliteration: 'Tzidkiyahu', english: 'Zedekiah', meaning: 'My righteousness is Yah', gender: 'male', nameType: 'english' },
  { id: '78', hebrew: 'נדב', transliteration: 'Nadav', english: 'Nadab', meaning: 'He volunteered', gender: 'male', nameType: 'english' },
  { id: '79', hebrew: 'אביהו', transliteration: 'Abihu', english: 'Abihu', meaning: 'Father is he', gender: 'male', nameType: 'english' },
  { id: '80', hebrew: 'אלעזר', transliteration: 'Elazar', english: 'Eleazar', meaning: 'God helps', gender: 'male', nameType: 'english' },
  { id: '81', hebrew: 'איתמר', transliteration: 'Itamar', english: 'Ithamar', meaning: 'Palm island', gender: 'male', nameType: 'english' },
  { id: '82', hebrew: 'מתתיהו', transliteration: 'Matityahu', english: 'Matthias', meaning: 'Gift of God', gender: 'male', nameType: 'english' },
  { id: '83', hebrew: 'שמעון', transliteration: 'Shimon', english: 'Simeon', meaning: 'He has heard', gender: 'male', nameType: 'english' },
  { id: '84', hebrew: 'רובן', transliteration: 'Reuven', english: 'Reuben', meaning: 'Behold a son', gender: 'male', nameType: 'english' },
  { id: '85', hebrew: 'יששכר', transliteration: 'Yisaschar', english: 'Issachar', meaning: 'He has hired', gender: 'male', nameType: 'english' },
  { id: '86', hebrew: 'זבולון', transliteration: 'Zevulun', english: 'Zebulun', meaning: 'Dwelling place', gender: 'male', nameType: 'english' },
  { id: '87', hebrew: 'דן', transliteration: 'Dan', english: 'Dan', meaning: 'Judge', gender: 'male', nameType: 'english' },
  { id: '88', hebrew: 'אשר', transliteration: 'Asher', english: 'Asher', meaning: 'Happy', gender: 'male', nameType: 'english' },
  { id: '89', hebrew: 'דינה', transliteration: 'Dina', english: 'Dinah', meaning: 'Judged', gender: 'female', nameType: 'english' },
  { id: '90', hebrew: 'יעל', transliteration: 'Yael', english: 'Yael', meaning: 'Mountain goat', gender: 'female', nameType: 'english' },
  { id: '91', hebrew: 'אורי', transliteration: 'Uri', english: 'Uri', meaning: 'My light', gender: 'male', nameType: 'english' },
  { id: '92', hebrew: 'דליה', transliteration: 'Dalya', english: 'Dalya', meaning: 'Branch of God', gender: 'female', nameType: 'english' },
  { id: '93', hebrew: 'גילי', transliteration: 'Gili', english: 'Gili', meaning: 'Joy is mine', gender: 'female', nameType: 'english' },
  { id: '94', hebrew: 'שחר', transliteration: 'Shachar', english: 'Shachar', meaning: 'Dawn', gender: 'male', nameType: 'english' },
  { id: '95', hebrew: 'טוביה', transliteration: 'Tuviya', english: 'Tobias', meaning: 'God is good', gender: 'male', nameType: 'english' },
  { id: '96', hebrew: 'אביתר', transliteration: 'Evyatar', english: 'Abiathar', meaning: 'Father is great', gender: 'male', nameType: 'english' },
  { id: '97', hebrew: 'צדוק', transliteration: 'Tzadok', english: 'Zadok', meaning: 'Righteous', gender: 'male', nameType: 'english' },
  { id: '98', hebrew: 'אבשלום', transliteration: 'Avshalom', english: 'Absalom', meaning: 'Father of peace', gender: 'male', nameType: 'english' },
  { id: '99', hebrew: 'יוליוס', transliteration: 'Yulius', english: 'Julius', meaning: 'Youthful', gender: 'male', nameType: 'english' },
  { id: '100', hebrew: 'דנייל', transliteration: 'Danyel', english: 'Daniel', meaning: 'God is judge', gender: 'male', nameType: 'english' },
  { id: '101', hebrew: 'לוקס', transliteration: 'Lukas', english: 'Lucas', meaning: 'Man from Lucania', gender: 'male', nameType: 'english' },
  { id: '102', hebrew: 'מרקוס', transliteration: 'Markos', english: 'Marcus', meaning: 'Of Mars', gender: 'male', nameType: 'english' },
  { id: '103', hebrew: 'אנטוניוס', transliteration: 'Antonyos', english: 'Anthony', meaning: 'Priceless', gender: 'male', nameType: 'english' },
  { id: '104', hebrew: 'פטרוס', transliteration: 'Petros', english: 'Peter', meaning: 'Stone', gender: 'male', nameType: 'english' },
  { id: '105', hebrew: 'אנדריאס', transliteration: 'Andreas', english: 'Andrew', meaning: 'Strong man', gender: 'male', nameType: 'english' },
  { id: '106', hebrew: 'סימון', transliteration: 'Simon', english: 'Simon', meaning: 'He heard', gender: 'male', nameType: 'english' },
  { id: '107', hebrew: 'יוסף', transliteration: 'Yosef', english: 'Joe', meaning: 'God increases', gender: 'male', nameType: 'english' },
  { id: '108', hebrew: 'יוחנן', transliteration: 'Yochanan', english: 'John', meaning: 'God is gracious', gender: 'male', nameType: 'english' },
  { id: '109', hebrew: 'תומס', transliteration: 'Thomas', english: 'Thomas', meaning: 'Twin', gender: 'male', nameType: 'english' },
  { id: '110', hebrew: 'אליהו', transliteration: 'Eliyahu', english: 'Elijah', meaning: 'My God is Yah', gender: 'male', nameType: 'english' },
  { id: '111', hebrew: 'מרי', transliteration: 'Mary', english: 'Mary', meaning: 'Star of the sea', gender: 'female', nameType: 'english' },
  { id: '112', hebrew: 'אליזבת', transliteration: 'Elizabeth', english: 'Elizabeth', meaning: 'God\'s oath', gender: 'female', nameType: 'english' },
  { id: '113', hebrew: 'יוהנה', transliteration: 'Johanna', english: 'Joanna', meaning: 'God is gracious', gender: 'female', nameType: 'english' },
  { id: '114', hebrew: 'קתרין', transliteration: 'Katherine', english: 'Catherine', meaning: 'Pure', gender: 'female', nameType: 'english' },
  { id: '115', hebrew: 'סוזנה', transliteration: 'Susanna', english: 'Susanna', meaning: 'Lily', gender: 'female', nameType: 'english' },
  { id: '116', hebrew: 'ססיליה', transliteration: 'Sesilia', english: 'Cecilia', meaning: 'Blind', gender: 'female', nameType: 'english' },
  { id: '117', hebrew: 'יוהנה', transliteration: 'Yahanna', english: 'Hannah', meaning: 'Gracious', gender: 'female', nameType: 'english' },
  { id: '118', hebrew: 'לוציה', transliteration: 'Lucia', english: 'Lucy', meaning: 'Light', gender: 'female', nameType: 'english' },
  { id: '119', hebrew: 'רוז', transliteration: 'Roz', english: 'Rose', meaning: 'Flower', gender: 'female', nameType: 'english' },
  { id: '120', hebrew: 'לילי', transliteration: 'Lili', english: 'Lily', meaning: 'Flower', gender: 'female', nameType: 'english' },
  { id: '121', hebrew: 'אוליביה', transliteration: 'Olivya', english: 'Olivia', meaning: 'Olive', gender: 'female', nameType: 'english' },
  { id: '122', hebrew: 'סופיה', transliteration: 'Sofya', english: 'Sophia', meaning: 'Wisdom', gender: 'female', nameType: 'english' },
  { id: '123', hebrew: 'אמילי', transliteration: 'Emili', english: 'Emily', meaning: 'Rival', gender: 'female', nameType: 'english' },
  { id: '124', hebrew: 'אביגיל', transliteration: 'Avigail', english: 'Abigail', meaning: 'Father\'s joy', gender: 'female', nameType: 'english' },
  { id: '125', hebrew: 'ז\'קלוד', transliteration: 'Claude', english: 'Claude', meaning: 'Lame', gender: 'male', nameType: 'english' },
  { id: '126', hebrew: 'פול', transliteration: 'Paul', english: 'Paul', meaning: 'Small', gender: 'male', nameType: 'english' },
  { id: '127', hebrew: 'קרלוס', transliteration: 'Carlos', english: 'Charles', meaning: 'Free man', gender: 'male', nameType: 'english' },
  { id: '128', hebrew: 'רוברט', transliteration: 'Robert', english: 'Robert', meaning: 'Bright fame', gender: 'male', nameType: 'english' },
  { id: '129', hebrew: 'וויליאם', transliteration: 'William', english: 'William', meaning: 'Resolute protector', gender: 'male', nameType: 'english' },
  { id: '130', hebrew: 'ריצ\'רד', transliteration: 'Richard', english: 'Richard', meaning: 'Brave ruler', gender: 'male', nameType: 'english' },
  { id: '131', hebrew: 'קינת\'ון', transliteration: 'Kingston', english: 'Kingston', meaning: 'King\'s settlement', gender: 'male', nameType: 'english' },
  { id: '132', hebrew: 'אדוארד', transliteration: 'Edward', english: 'Edward', meaning: 'Wealthy guardian', gender: 'male', nameType: 'english' },
  { id: '133', hebrew: 'יוליוס', transliteration: 'Julius', english: 'Julian', meaning: 'Youthful', gender: 'male', nameType: 'english' },
  { id: '134', hebrew: 'ליאוני', transliteration: 'Leoni', english: 'Leonard', meaning: 'Brave lion', gender: 'male', nameType: 'english' },
  { id: '135', hebrew: 'אדם', transliteration: 'Adam', english: 'Adam', meaning: 'Man', gender: 'male', nameType: 'english' },
  { id: '136', hebrew: 'אברהם', transliteration: 'Abraham', english: 'Abraham', meaning: 'Father of many', gender: 'male', nameType: 'english' },
  { id: '137', hebrew: 'אביב', transliteration: 'Aviv', english: 'Aviv', meaning: 'Spring', gender: 'male', nameType: 'english' },
  { id: '138', hebrew: 'ניתן', transliteration: 'Natan', english: 'Nathan', meaning: 'He gave', gender: 'male', nameType: 'english' },
  { id: '139', hebrew: 'צדיק', transliteration: 'Tzaddiq', english: 'Tzaddiq', meaning: 'Righteous', gender: 'male', nameType: 'english' },
  { id: '140', hebrew: 'אוריאל', transliteration: 'Uriel', english: 'Uriel', meaning: 'God is my light', gender: 'male', nameType: 'english' },
  { id: '141', hebrew: 'גבריאל', transliteration: 'Gabriel', english: 'Gabriel', meaning: 'God is my strength', gender: 'male', nameType: 'english' },
  { id: '142', hebrew: 'רפאל', transliteration: 'Raphael', english: 'Raphael', meaning: 'God heals', gender: 'male', nameType: 'english' },
  { id: '143', hebrew: 'צריאל', transliteration: 'Tzuriel', english: 'Tzuriel', meaning: 'God is my rock', gender: 'male', nameType: 'english' },
  { id: '144', hebrew: 'סמאל', transliteration: 'Samuel', english: 'Samuel', meaning: 'God has heard', gender: 'male', nameType: 'english' },
  { id: '145', hebrew: 'שם', transliteration: 'Shem', english: 'Shem', meaning: 'Name', gender: 'male', nameType: 'english' },
  { id: '146', hebrew: 'חם', transliteration: 'Ham', english: 'Ham', meaning: 'Hot', gender: 'male', nameType: 'english' },
  { id: '147', hebrew: 'יפת', transliteration: 'Yafet', english: 'Japheth', meaning: 'Expansion', gender: 'male', nameType: 'english' },
  { id: '148', hebrew: 'תמר', transliteration: 'Tamar', english: 'Tamar', meaning: 'Palm tree', gender: 'female', nameType: 'english' },
  { id: '149', hebrew: 'שירה', transliteration: 'Shira', english: 'Shira', meaning: 'Song', gender: 'female', nameType: 'english' },
  { id: '150', hebrew: 'אליס', transliteration: 'Elis', english: 'Alice', meaning: 'Noble', gender: 'female', nameType: 'english' },
  
  // Hebrew Names (100+)
  { id: '151', hebrew: 'אברהם', transliteration: 'Avraham', english: 'Abraham', meaning: 'Father of multitude', gender: 'male', nameType: 'hebrew' },
  { id: '152', hebrew: 'יצחק', transliteration: 'Yitzhak', english: 'Isaac', meaning: 'He will laugh', gender: 'male', nameType: 'hebrew' },
  { id: '153', hebrew: 'יעקב', transliteration: 'Yaakov', english: 'Jacob', meaning: 'Supplanter', gender: 'male', nameType: 'hebrew' },
  { id: '154', hebrew: 'יהודה', transliteration: 'Yehuda', english: 'Judah', meaning: 'Praised', gender: 'male', nameType: 'hebrew' },
  { id: '155', hebrew: 'יוסף', transliteration: 'Yosef', english: 'Joseph', meaning: 'God increases', gender: 'male', nameType: 'hebrew' },
  { id: '156', hebrew: 'משה', transliteration: 'Moshe', english: 'Moses', meaning: 'Drawn out', gender: 'male', nameType: 'hebrew' },
  { id: '157', hebrew: 'דוד', transliteration: 'David', english: 'David', meaning: 'Beloved', gender: 'male', nameType: 'hebrew' },
  { id: '158', hebrew: 'שלמה', transliteration: 'Shlomo', english: 'Solomon', meaning: 'Peaceful', gender: 'male', nameType: 'hebrew' },
  { id: '159', hebrew: 'אליהו', transliteration: 'Eliyahu', english: 'Elijah', meaning: 'My God is Yah', gender: 'male', nameType: 'hebrew' },
  { id: '160', hebrew: 'אלישע', transliteration: 'Elisha', english: 'Elisha', meaning: 'God is salvation', gender: 'male', nameType: 'hebrew' },
  { id: '161', hebrew: 'יחזקאל', transliteration: 'Yechezkel', english: 'Ezekiel', meaning: 'God strengthens', gender: 'male', nameType: 'hebrew' },
  { id: '162', hebrew: 'ירמיה', transliteration: 'Yirmiya', english: 'Jeremiah', meaning: 'God will exalt', gender: 'male', nameType: 'hebrew' },
  { id: '163', hebrew: 'ישעיה', transliteration: 'Yeshaya', english: 'Isaiah', meaning: 'God is salvation', gender: 'male', nameType: 'hebrew' },
  { id: '164', hebrew: 'שמואל', transliteration: 'Shmuel', english: 'Samuel', meaning: 'God has heard', gender: 'male', nameType: 'hebrew' },
  { id: '165', hebrew: 'בנימין', transliteration: 'Binyamin', english: 'Benjamin', meaning: 'Son of the right hand', gender: 'male', nameType: 'hebrew' },
  { id: '166', hebrew: 'רובן', transliteration: 'Reuven', english: 'Reuben', meaning: 'Behold a son', gender: 'male', nameType: 'hebrew' },
  { id: '167', hebrew: 'שמעון', transliteration: 'Shimon', english: 'Simeon', meaning: 'He has heard', gender: 'male', nameType: 'hebrew' },
  { id: '168', hebrew: 'לוי', transliteration: 'Levi', english: 'Levi', meaning: 'Joined', gender: 'male', nameType: 'hebrew' },
  { id: '169', hebrew: 'יששכר', transliteration: 'Yisaschar', english: 'Issachar', meaning: 'He has hired', gender: 'male', nameType: 'hebrew' },
  { id: '170', hebrew: 'זבולון', transliteration: 'Zevulun', english: 'Zebulun', meaning: 'Dwelling place', gender: 'male', nameType: 'hebrew' },
  { id: '171', hebrew: 'דן', transliteration: 'Dan', english: 'Dan', meaning: 'Judge', gender: 'male', nameType: 'hebrew' },
  { id: '172', hebrew: 'נפתלי', transliteration: 'Naftali', english: 'Naphtali', meaning: 'My struggle', gender: 'male', nameType: 'hebrew' },
  { id: '173', hebrew: 'גד', transliteration: 'Gad', english: 'Gad', meaning: 'Fortune', gender: 'male', nameType: 'hebrew' },
  { id: '174', hebrew: 'אשר', transliteration: 'Asher', english: 'Asher', meaning: 'Happy', gender: 'male', nameType: 'hebrew' },
  { id: '175', hebrew: 'אפרים', transliteration: 'Ephraim', english: 'Ephraim', meaning: 'Fruitful', gender: 'male', nameType: 'hebrew' },
  { id: '176', hebrew: 'מנשה', transliteration: 'Menashe', english: 'Manasseh', meaning: 'Making forget', gender: 'male', nameType: 'hebrew' },
  { id: '177', hebrew: 'מלאכי', transliteration: 'Malachi', english: 'Malachi', meaning: 'My messenger', gender: 'male', nameType: 'hebrew' },
  { id: '178', hebrew: 'הושע', transliteration: 'Hosea', english: 'Hosea', meaning: 'Salvation', gender: 'male', nameType: 'hebrew' },
  { id: '179', hebrew: 'יוחנן', transliteration: 'Yochanan', english: 'John', meaning: 'God is gracious', gender: 'male', nameType: 'hebrew' },
  { id: '180', hebrew: 'נחום', transliteration: 'Nachum', english: 'Nahum', meaning: 'Comfort', gender: 'male', nameType: 'hebrew' },
  { id: '181', hebrew: 'חביקוק', transliteration: 'Chavakuk', english: 'Habakkuk', meaning: 'Embrace', gender: 'male', nameType: 'hebrew' },
  { id: '182', hebrew: 'צפניה', transliteration: 'Tzfanya', english: 'Zephaniah', meaning: 'Hidden by God', gender: 'male', nameType: 'hebrew' },
  { id: '183', hebrew: 'חגי', transliteration: 'Chagai', english: 'Haggai', meaning: 'My festival', gender: 'male', nameType: 'hebrew' },
  { id: '184', hebrew: 'זכריה', transliteration: 'Zecharya', english: 'Zechariah', meaning: 'God remembers', gender: 'male', nameType: 'hebrew' },
  { id: '185', hebrew: 'שרה', transliteration: 'Sara', english: 'Sarah', meaning: 'Princess', gender: 'female', nameType: 'hebrew' },
  { id: '186', hebrew: 'רבקה', transliteration: 'Rivka', english: 'Rebecca', meaning: 'To tie', gender: 'female', nameType: 'hebrew' },
  { id: '187', hebrew: 'לאה', transliteration: 'Leah', english: 'Leah', meaning: 'Weary', gender: 'female', nameType: 'hebrew' },
  { id: '188', hebrew: 'רחל', transliteration: 'Rachel', english: 'Rachel', meaning: 'Ewe', gender: 'female', nameType: 'hebrew' },
  { id: '189', hebrew: 'מרים', transliteration: 'Miriam', english: 'Miriam', meaning: 'Bitter sea', gender: 'female', nameType: 'hebrew' },
  { id: '190', hebrew: 'דבורה', transliteration: 'Devora', english: 'Deborah', meaning: 'Bee', gender: 'female', nameType: 'hebrew' },
  { id: '191', hebrew: 'רוט', transliteration: 'Rut', english: 'Ruth', meaning: 'Friend, companion', gender: 'female', nameType: 'hebrew' },
  { id: '192', hebrew: 'אסתר', transliteration: 'Esther', english: 'Esther', meaning: 'Star', gender: 'female', nameType: 'hebrew' },
  { id: '193', hebrew: 'חנה', transliteration: 'Chana', english: 'Hannah', meaning: 'Grace', gender: 'female', nameType: 'hebrew' },
  { id: '194', hebrew: 'יהודית', transliteration: 'Yehudit', english: 'Judith', meaning: 'Woman of Judea', gender: 'female', nameType: 'hebrew' },
  { id: '195', hebrew: 'תמר', transliteration: 'Tamar', english: 'Tamar', meaning: 'Date Palm', gender: 'female', nameType: 'hebrew' },
  { id: '196', hebrew: 'דינה', transliteration: 'Dina', english: 'Dinah', meaning: 'Judged', gender: 'female', nameType: 'hebrew' },
  { id: '197', hebrew: 'בתשבע', transliteration: 'Bat Sheva', english: 'Bathsheba', meaning: 'Daughter of oath', gender: 'female', nameType: 'hebrew' },
  { id: '198', hebrew: 'מיכל', transliteration: 'Michal', english: 'Michal', meaning: 'Who is like God', gender: 'female', nameType: 'hebrew' },
  { id: '199', hebrew: 'אביגיל', transliteration: 'Avigayil', english: 'Abigail', meaning: 'My father is joy', gender: 'female', nameType: 'hebrew' },
  { id: '200', hebrew: 'נועמי', transliteration: 'Noami', english: 'Naomi', meaning: 'Pleasantness', gender: 'female', nameType: 'hebrew' },
  { id: '201', hebrew: 'עפרה', transliteration: 'Ofra', english: 'Ophrah', meaning: 'Fawn', gender: 'female', nameType: 'hebrew' },
  { id: '202', hebrew: 'שושנה', transliteration: 'Shushana', english: 'Susanna', meaning: 'Lily', gender: 'female', nameType: 'hebrew' },
  { id: '203', hebrew: 'חולדה', transliteration: 'Chuld', english: 'Huldah', meaning: 'Weasel', gender: 'female', nameType: 'hebrew' },
  { id: '204', hebrew: 'מלכה', transliteration: 'Malka', english: 'Milcah', meaning: 'Queen', gender: 'female', nameType: 'hebrew' },
  { id: '205', hebrew: 'נועה', transliteration: 'Noa', english: 'Noah', meaning: 'Motion', gender: 'female', nameType: 'hebrew' },
  { id: '206', hebrew: 'תרצה', transliteration: 'Tirtza', english: 'Tirzah', meaning: 'Pleasantness', gender: 'female', nameType: 'hebrew' },
  { id: '207', hebrew: 'גומר', transliteration: 'Gomer', english: 'Gomer', meaning: 'Completion', gender: 'female', nameType: 'hebrew' },
  { id: '208', hebrew: 'זפורה', transliteration: 'Tzippora', english: 'Zipporah', meaning: 'Little bird', gender: 'female', nameType: 'hebrew' },
  { id: '209', hebrew: 'אתי', transliteration: 'Adi', english: 'Adi', meaning: 'My ornament', gender: 'female', nameType: 'hebrew' },
  { id: '210', hebrew: 'שירה', transliteration: 'Shira', english: 'Shira', meaning: 'Song', gender: 'female', nameType: 'hebrew' },
  { id: '211', hebrew: 'טליה', transliteration: 'Talia', english: 'Talia', meaning: 'Dew from God', gender: 'female', nameType: 'hebrew' },
  { id: '212', hebrew: 'אורית', transliteration: 'Orit', english: 'Orit', meaning: 'My light', gender: 'female', nameType: 'hebrew' },
  { id: '213', hebrew: 'מיה', transliteration: 'Maya', english: 'Maya', meaning: 'Water', gender: 'female', nameType: 'hebrew' },
  { id: '214', hebrew: 'גילה', transliteration: 'Gila', english: 'Gila', meaning: 'Joy', gender: 'female', nameType: 'hebrew' },
  { id: '215', hebrew: 'אמנה', transliteration: 'Emuna', english: 'Emunah', meaning: 'Faith', gender: 'female', nameType: 'hebrew' },
  { id: '216', hebrew: 'חיה', transliteration: 'Chaya', english: 'Chaya', meaning: 'Living', gender: 'female', nameType: 'hebrew' },
  { id: '217', hebrew: 'בתיה', transliteration: 'Bati', english: 'Bitya', meaning: 'Daughter of God', gender: 'female', nameType: 'hebrew' },
  { id: '218', hebrew: 'יונה', transliteration: 'Yona', english: 'Yona', meaning: 'Dove', gender: 'male', nameType: 'hebrew' },
  { id: '219', hebrew: 'אריאל', transliteration: 'Ariel', english: 'Ariel', meaning: 'Lion of God', gender: 'neutral', nameType: 'hebrew' },
  { id: '220', hebrew: 'אורי', transliteration: 'Uri', english: 'Uri', meaning: 'My light', gender: 'male', nameType: 'hebrew' },
  { id: '221', hebrew: 'נועם', transliteration: 'Noam', english: 'Noam', meaning: 'Pleasantness', gender: 'male', nameType: 'hebrew' },
  { id: '222', hebrew: 'אדר', transliteration: 'Adar', english: 'Adar', meaning: 'Majestic', gender: 'male', nameType: 'hebrew' },
  { id: '223', hebrew: 'אדון', transliteration: 'Adon', english: 'Adon', meaning: 'Master', gender: 'male', nameType: 'hebrew' },
  { id: '224', hebrew: 'אברם', transliteration: 'Avram', english: 'Avram', meaning: 'High father', gender: 'male', nameType: 'hebrew' },
  { id: '225', hebrew: 'אברהמיץ', transliteration: 'Avramovitz', english: 'Avramovitz', meaning: 'Son of Avram', gender: 'male', nameType: 'hebrew' },
  { id: '226', hebrew: 'אחאב', transliteration: 'Achav', english: 'Achav', meaning: 'Father\'s brother', gender: 'male', nameType: 'hebrew' },
  { id: '227', hebrew: 'אחי', transliteration: 'Achi', english: 'Achi', meaning: 'My brother', gender: 'male', nameType: 'hebrew' },
  { id: '228', hebrew: 'אחים', transliteration: 'Achim', english: 'Achim', meaning: 'God will establish', gender: 'male', nameType: 'hebrew' },
  { id: '229', hebrew: 'אחיטוב', transliteration: 'Achituv', english: 'Ahitub', meaning: 'My brother is goodness', gender: 'male', nameType: 'hebrew' },
  { id: '230', hebrew: 'אחד', transliteration: 'Echad', english: 'Echad', meaning: 'One', gender: 'male', nameType: 'hebrew' },
  { id: '231', hebrew: 'אל', transliteration: 'El', english: 'El', meaning: 'God', gender: 'neutral', nameType: 'hebrew' },
  { id: '232', hebrew: 'אלדד', transliteration: 'Eldad', english: 'Eldad', meaning: 'God loves', gender: 'male', nameType: 'hebrew' },
  { id: '233', hebrew: 'אלדון', transliteration: 'Eldon', english: 'Eldon', meaning: 'Old friend', gender: 'male', nameType: 'hebrew' },
  { id: '234', hebrew: 'אלדים', transliteration: 'Eldim', english: 'Eldin', meaning: 'Old friend', gender: 'male', nameType: 'hebrew' },
  { id: '235', hebrew: 'אלויים', transliteration: 'Eloim', english: 'Elohim', meaning: 'God', gender: 'neutral', nameType: 'hebrew' },
  { id: '236', hebrew: 'אלונה', transliteration: 'Alona', english: 'Alona', meaning: 'Oak tree', gender: 'female', nameType: 'hebrew' },
  { id: '237', hebrew: 'אלונית', transliteration: 'Alonit', english: 'Alonit', meaning: 'Little oak', gender: 'female', nameType: 'hebrew' },
  { id: '238', hebrew: 'אלה', transliteration: 'Alah', english: 'Alah', meaning: 'Oak tree', gender: 'female', nameType: 'hebrew' },
  { id: '239', hebrew: 'אליב', transliteration: 'Aliv', english: 'Aliv', meaning: 'Olive tree', gender: 'male', nameType: 'hebrew' },
  { id: '240', hebrew: 'אליבה', transliteration: 'Aliba', english: 'Aliba', meaning: 'Olive', gender: 'female', nameType: 'hebrew' },
  { id: '241', hebrew: 'אלף', transliteration: 'Alf', english: 'Alf', meaning: 'First letter', gender: 'male', nameType: 'hebrew' },
  { id: '242', hebrew: 'אלפא', transliteration: 'Alfa', english: 'Alfa', meaning: 'First', gender: 'female', nameType: 'hebrew' },
  { id: '243', hebrew: 'אל שדי', transliteration: 'El Shaddai', english: 'El Shaddai', meaning: 'God Almighty', gender: 'neutral', nameType: 'hebrew' },
  { id: '244', hebrew: 'אלתיה', transliteration: 'Alti', english: 'Alti', meaning: 'My God', gender: 'female', nameType: 'hebrew' },
  { id: '245', hebrew: 'אלתיו', transliteration: 'Altio', english: 'Altio', meaning: 'My God', gender: 'male', nameType: 'hebrew' },
  { id: '246', hebrew: 'אם', transliteration: 'Am', english: 'Am', meaning: 'People', gender: 'neutral', nameType: 'hebrew' },
  { id: '247', hebrew: 'אמא', transliteration: 'Amma', english: 'Amma', meaning: 'Mother', gender: 'female', nameType: 'hebrew' },
  { id: '248', hebrew: 'אמי', transliteration: 'Ami', english: 'Ami', meaning: 'My people', gender: 'male', nameType: 'hebrew' },
  { id: '249', hebrew: 'אמיא', transliteration: 'Amia', english: 'Amia', meaning: 'My people', gender: 'female', nameType: 'hebrew' },
  { id: '250', hebrew: 'אמיל', transliteration: 'Amil', english: 'Amil', meaning: 'Work', gender: 'male', nameType: 'hebrew' },
];
