export interface NameData {
  id: string;
  hebrew: string;
  transliteration: string;
  english: string;
  meaning: string;
  gender: 'male' | 'female' | 'neutral';
  nameType: 'english' | 'hebrew';
}

export const NAMES: NameData[] = [
  { id: '1', hebrew: 'אריאל', transliteration: 'Ariel', english: 'Ariel', meaning: 'Lion of God', gender: 'neutral', nameType: 'english' },
  { id: '2', hebrew: 'נועה', transliteration: 'Noa', english: 'Noa', meaning: 'Motion, Movement', gender: 'female', nameType: 'english' },
  { id: '3', hebrew: 'דוד', transliteration: 'David', english: 'David', meaning: 'Beloved', gender: 'male', nameType: 'english' },
  { id: '4', hebrew: 'שרה', transliteration: 'Sarah', english: 'Sarah', meaning: 'Princess', gender: 'female', nameType: 'english' },
  { id: '5', hebrew: 'יוסף', transliteration: 'Yosef', english: 'Joseph', meaning: 'He will add', gender: 'male', nameType: 'english' },
  { id: '6', hebrew: 'חנה', transliteration: 'Chana', english: 'Hannah', meaning: 'Grace', gender: 'female', nameType: 'english' },
  { id: '7', hebrew: 'בנימין', transliteration: 'Binyamin', english: 'Benjamin', meaning: 'Son of the right hand', gender: 'male', nameType: 'english' },
  { id: '8', hebrew: 'רחל', transliteration: 'Rachel', english: 'Rachel', meaning: 'Ewe', gender: 'female', nameType: 'english' },
  { id: '9', hebrew: 'איתן', transliteration: 'Eitan', english: 'Ethan', meaning: 'Strong, Enduring', gender: 'male', nameType: 'english' },
  { id: '10', hebrew: 'מיה', transliteration: 'Maya', english: 'Maya', meaning: 'Water', gender: 'female', nameType: 'english' },
  { id: '11', hebrew: 'אביב', transliteration: 'Aviv', english: 'Aviv', meaning: 'Spring', gender: 'neutral', nameType: 'english' },
  { id: '12', hebrew: 'תמר', transliteration: 'Tamar', english: 'Tamar', meaning: 'Date Palm', gender: 'female', nameType: 'english' },
  { id: '13', hebrew: 'עומר', transliteration: 'Omer', english: 'Omer', meaning: 'Sheaf of wheat', gender: 'male', nameType: 'english' },
  { id: '14', hebrew: 'שירה', transliteration: 'Shira', english: 'Shira', meaning: 'Song, Poetry', gender: 'female', nameType: 'english' },
  { id: '15', hebrew: 'מיכאל', transliteration: 'Michael', english: 'Michael', meaning: 'Who is like God?', gender: 'male', nameType: 'english' },
  { id: '16', hebrew: 'לאה', transliteration: 'Leah', english: 'Leah', meaning: 'Weary', gender: 'female', nameType: 'english' },
  { id: '17', hebrew: 'יצחק', transliteration: 'Yitzhak', english: 'Isaac', meaning: 'He will laugh', gender: 'male', nameType: 'english' },
  { id: '18', hebrew: 'רבקה', transliteration: 'Rivka', english: 'Rebecca', meaning: 'To tie', gender: 'female', nameType: 'english' },
  { id: '19', hebrew: 'יעקב', transliteration: 'Yaakov', english: 'Jacob', meaning: 'To follow', gender: 'male', nameType: 'english' },
  { id: '20', hebrew: 'אסתר', transliteration: 'Esther', english: 'Esther', meaning: 'Star', gender: 'female', nameType: 'english' },
  { id: '21', hebrew: 'אברהם', transliteration: 'Avraham', english: 'Abraham', meaning: 'Father of many', gender: 'male', nameType: 'english' },
  { id: '22', hebrew: 'מרים', transliteration: 'Miriam', english: 'Miriam', meaning: 'Bitter sea', gender: 'female', nameType: 'english' },
  { id: '23', hebrew: 'משה', transliteration: 'Moshe', english: 'Moses', meaning: 'Drawn from water', gender: 'male', nameType: 'english' },
  { id: '24', hebrew: 'אלי', transliteration: 'Eli', english: 'Eli', meaning: 'Ascent', gender: 'male', nameType: 'english' },
  { id: '25', hebrew: 'טליה', transliteration: 'Talia', english: 'Talia', meaning: 'Dew from God', gender: 'female', nameType: 'english' },
  { id: '26', hebrew: 'דניאל', transliteration: 'Daniel', english: 'Daniel', meaning: 'God is my judge', gender: 'male', nameType: 'english' },
  { id: '27', hebrew: 'יהודית', transliteration: 'Yehudit', english: 'Judith', meaning: 'Woman of Judea', gender: 'female', nameType: 'english' },
  { id: '28', hebrew: 'שלמה', transliteration: 'Shlomo', english: 'Solomon', meaning: 'Peaceful', gender: 'male', nameType: 'english' },
  { id: '29', hebrew: 'בתשבע', transliteration: 'Batsheva', english: 'Bathsheba', meaning: 'Daughter of oath', gender: 'female', nameType: 'english' },
  { id: '30', hebrew: 'יונה', transliteration: 'Yona', english: 'Jonah', meaning: 'Dove', gender: 'male', nameType: 'english' },
  { id: '31', hebrew: 'יהודה', transliteration: 'Yehuda', english: 'Judah', meaning: 'Praised', gender: 'male', nameType: 'english' },
  { id: '32', hebrew: 'סוזן', transliteration: 'Suzan', english: 'Susan', meaning: 'Graceful lily', gender: 'female', nameType: 'english' },
  { id: '33', hebrew: 'אפרים', transliteration: 'Ephraim', english: 'Ephraim', meaning: 'Fruitful', gender: 'male', nameType: 'english' },
  { id: '34', hebrew: 'אמנון', transliteration: 'Amnon', english: 'Amnon', meaning: 'Faithful', gender: 'male', nameType: 'english' },
  { id: '35', hebrew: 'מנשה', transliteration: 'Menashe', english: 'Manasseh', meaning: 'Making forget', gender: 'male', nameType: 'english' },
  { id: '36', hebrew: 'אסף', transliteration: 'Asaf', english: 'Asaph', meaning: 'Gatherer', gender: 'male', nameType: 'english' },
  { id: '37', hebrew: 'דבורה', transliteration: 'Devora', english: 'Deborah', meaning: 'Bee', gender: 'female', nameType: 'english' },
  { id: '38', hebrew: 'ג\'אד', transliteration: 'Gad', english: 'Gad', meaning: 'Fortune', gender: 'male', nameType: 'english' },
  { id: '39', hebrew: 'נפתלי', transliteration: 'Naftali', english: 'Naphtali', meaning: 'My struggle', gender: 'male', nameType: 'english' },
  { id: '40', hebrew: 'רוט', transliteration: 'Rut', english: 'Ruth', meaning: 'Friend, companion', gender: 'female', nameType: 'english' },
  { id: '41', hebrew: 'צפניה', transliteration: 'Tzfanya', english: 'Zephaniah', meaning: 'Hidden by God', gender: 'male', nameType: 'english' },
  { id: '42', hebrew: 'עובדיה', transliteration: 'Obadya', english: 'Obadiah', meaning: 'Servant of God', gender: 'male', nameType: 'english' },
  { id: '43', hebrew: 'מלאכי', transliteration: 'Malachi', english: 'Malachi', meaning: 'My messenger', gender: 'male', nameType: 'english' },
  { id: '44', hebrew: 'ירמיה', transliteration: 'Yirmiya', english: 'Jeremiah', meaning: 'God will exalt', gender: 'male', nameType: 'english' },
  { id: '45', hebrew: 'יחזקאל', transliteration: 'Yechezkel', english: 'Ezekiel', meaning: 'God strengthens', gender: 'male', nameType: 'english' },
  { id: '46', hebrew: 'דוד', transliteration: 'Dovid', english: 'David', meaning: 'Beloved', gender: 'male', nameType: 'english' },
  { id: '47', hebrew: 'שמואל', transliteration: 'Shmuel', english: 'Samuel', meaning: 'God has heard', gender: 'male', nameType: 'english' },
  { id: '48', hebrew: 'שאול', transliteration: 'Shaul', english: 'Saul', meaning: 'Asked for', gender: 'male', nameType: 'english' },
  { id: '49', hebrew: 'עזריה', transliteration: 'Azarya', english: 'Azariah', meaning: 'God helps', gender: 'male', nameType: 'english' },
  { id: '50', hebrew: 'חזקיה', transliteration: 'Hezekiah', english: 'Hezekiah', meaning: 'God strengthens', gender: 'male', nameType: 'english' },
  { id: '51', hebrew: 'יוסיה', transliteration: 'Yoshiyahu', english: 'Josiah', meaning: 'God supports', gender: 'male', nameType: 'english' },
  { id: '52', hebrew: 'שלום', transliteration: 'Shalom', english: 'Shalom', meaning: 'Peace', gender: 'neutral', nameType: 'english' },
  { id: '53', hebrew: 'אור', transliteration: 'Or', english: 'Or', meaning: 'Light', gender: 'neutral', nameType: 'english' },
  { id: '54', hebrew: 'אתי', transliteration: 'Adi', english: 'Adi', meaning: 'My jewel', gender: 'female', nameType: 'english' },
  { id: '55', hebrew: 'יד', transliteration: 'Yad', english: 'Yad', meaning: 'Hand', gender: 'neutral', nameType: 'english' },
  { id: '56', hebrew: 'נמרוד', transliteration: 'Nimrod', english: 'Nimrod', meaning: 'Mighty hunter', gender: 'male', nameType: 'english' },
  { id: '57', hebrew: 'בלעם', transliteration: 'Bilam', english: 'Balaam', meaning: 'Not of the people', gender: 'male', nameType: 'english' },
  { id: '58', hebrew: 'קרח', transliteration: 'Korach', english: 'Korah', meaning: 'Baldness', gender: 'male', nameType: 'english' },
  { id: '59', hebrew: 'אנוש', transliteration: 'Enosh', english: 'Enosh', meaning: 'Mortal man', gender: 'male', nameType: 'english' },
  { id: '60', hebrew: 'מתושלח', transliteration: 'Metushelach', english: 'Methuselah', meaning: 'Man of the dart', gender: 'male', nameType: 'english' },
  { id: '61', hebrew: 'נח', transliteration: 'Noach', english: 'Noah', meaning: 'Rest, comfort', gender: 'male', nameType: 'english' },
  { id: '62', hebrew: 'לוט', transliteration: 'Lot', english: 'Lot', meaning: 'Concealed', gender: 'male', nameType: 'english' },
  { id: '63', hebrew: 'מלכי צדק', transliteration: 'Malki Tzedek', english: 'Melchizedek', meaning: 'My king is righteous', gender: 'male', nameType: 'english' },
  { id: '64', hebrew: 'יהוידע', transliteration: 'Yehoyada', english: 'Jehoiada', meaning: 'God knows', gender: 'male', nameType: 'english' },
  { id: '65', hebrew: 'יהונתן', transliteration: 'Yehonatan', english: 'Jonathan', meaning: 'God gave', gender: 'male', nameType: 'english' },
  { id: '66', hebrew: 'אבינדב', transliteration: 'Abinadav', english: 'Abinadab', meaning: 'Father of willingness', gender: 'male', nameType: 'english' },
  { id: '67', hebrew: 'עמרי', transliteration: 'Omri', english: 'Omri', meaning: 'Sheaf of God', gender: 'male', nameType: 'english' },
  { id: '68', hebrew: 'אחאב', transliteration: 'Ahav', english: 'Ahab', meaning: 'Father\'s brother', gender: 'male', nameType: 'english' },
  { id: '69', hebrew: 'יהורם', transliteration: 'Yehoram', english: 'Jehoram', meaning: 'God is exalted', gender: 'male', nameType: 'english' },
  { id: '70', hebrew: 'יהוש', transliteration: 'Yehosh', english: 'Jehoash', meaning: 'God gives', gender: 'male', nameType: 'english' },
  { id: '71', hebrew: 'יהו', transliteration: 'Yehu', english: 'Jehu', meaning: 'He is Yah', gender: 'male', nameType: 'english' },
  { id: '72', hebrew: 'יוטם', transliteration: 'Yotam', english: 'Jotham', meaning: 'God is perfect', gender: 'male', nameType: 'english' },
  { id: '73', hebrew: 'אחז', transliteration: 'Achaz', english: 'Ahaz', meaning: 'God grasps', gender: 'male', nameType: 'english' },
  { id: '74', hebrew: 'שנאצר', transliteration: 'Sennacherib', english: 'Sennacherib', meaning: 'Sin has replaced brothers', gender: 'male', nameType: 'english' },
  { id: '75', hebrew: 'נבוכדנצר', transliteration: 'Nebuchadnezzar', english: 'Nebuchadnezzar', meaning: 'Nabu protect the son', gender: 'male', nameType: 'english' },
  { id: '76', hebrew: 'בלשצר', transliteration: 'Belshatzar', english: 'Belshazzar', meaning: 'Bel protect the king', gender: 'male', nameType: 'english' },
  { id: '77', hebrew: 'מרדכי', transliteration: 'Mordechai', english: 'Mordecai', meaning: 'Follower of Marduk', gender: 'male', nameType: 'english' },
  { id: '78', hebrew: 'מנחם', transliteration: 'Menachem', english: 'Menahem', meaning: 'Comforter', gender: 'male', nameType: 'english' },
  { id: '79', hebrew: 'צדקיה', transliteration: 'Tzidkiyahu', english: 'Zedekiah', meaning: 'My righteousness is Yah', gender: 'male', nameType: 'english' },
  { id: '80', hebrew: 'נדב', transliteration: 'Nadav', english: 'Nadab', meaning: 'He volunteered', gender: 'male', nameType: 'english' },
  { id: '81', hebrew: 'אביהו', transliteration: 'Abihu', english: 'Abihu', meaning: 'Father is he', gender: 'male', nameType: 'english' },
  { id: '82', hebrew: 'אלעזר', transliteration: 'Elazar', english: 'Eleazar', meaning: 'God helps', gender: 'male', nameType: 'english' },
  { id: '83', hebrew: 'איתמר', transliteration: 'Itamar', english: 'Ithamar', meaning: 'Palm island', gender: 'male', nameType: 'english' },
  { id: '84', hebrew: 'מתתיהו', transliteration: 'Matityahu', english: 'Matthias', meaning: 'Gift of God', gender: 'male', nameType: 'english' },
  { id: '85', hebrew: 'שמעון', transliteration: 'Shimon', english: 'Simeon', meaning: 'He has heard', gender: 'male', nameType: 'english' },
  { id: '86', hebrew: 'רובן', transliteration: 'Reuven', english: 'Reuben', meaning: 'Behold a son', gender: 'male', nameType: 'english' },
  { id: '87', hebrew: 'יששכר', transliteration: 'Yisaschar', english: 'Issachar', meaning: 'He has hired', gender: 'male', nameType: 'english' },
  { id: '88', hebrew: 'זבולון', transliteration: 'Zevulun', english: 'Zebulun', meaning: 'Dwelling place', gender: 'male', nameType: 'english' },
  { id: '89', hebrew: 'דן', transliteration: 'Dan', english: 'Dan', meaning: 'Judge', gender: 'male', nameType: 'english' },
  { id: '90', hebrew: 'אשר', transliteration: 'Asher', english: 'Asher', meaning: 'Happy', gender: 'male', nameType: 'english' },
  { id: '91', hebrew: 'דינה', transliteration: 'Dina', english: 'Dinah', meaning: 'Judged', gender: 'female', nameType: 'english' },
  { id: '92', hebrew: 'יעל', transliteration: 'Yael', english: 'Yael', meaning: 'Mountain goat', gender: 'female', nameType: 'english' },
  { id: '93', hebrew: 'אורי', transliteration: 'Uri', english: 'Uri', meaning: 'My light', gender: 'male', nameType: 'english' },
  { id: '94', hebrew: 'דליה', transliteration: 'Dalya', english: 'Dalya', meaning: 'Branch of God', gender: 'female', nameType: 'english' },
  { id: '95', hebrew: 'גילי', transliteration: 'Gili', english: 'Gili', meaning: 'Joy is mine', gender: 'female', nameType: 'english' },
  { id: '96', hebrew: 'שחר', transliteration: 'Shachar', english: 'Shachar', meaning: 'Dawn', gender: 'male', nameType: 'english' },
  { id: '97', hebrew: 'טוביה', transliteration: 'Tuviya', english: 'Tobias', meaning: 'God is good', gender: 'male', nameType: 'english' },
  { id: '98', hebrew: 'אביתר', transliteration: 'Evyatar', english: 'Abiathar', meaning: 'Father is great', gender: 'male', nameType: 'english' },
  { id: '99', hebrew: 'צדוק', transliteration: 'Tzadok', english: 'Zadok', meaning: 'Righteous', gender: 'male', nameType: 'english' },
  { id: '100', hebrew: 'אבשלום', transliteration: 'Avshalom', english: 'Absalom', meaning: 'Father of peace', gender: 'male', nameType: 'english' },

  // Hebrew names - traditional names used in religious rituals
  { id: '101', hebrew: 'אברהם', transliteration: 'Avraham', english: 'Abraham', meaning: 'Father of multitude', gender: 'male', nameType: 'hebrew' },
  { id: '102', hebrew: 'יצחק', transliteration: 'Yitzhak', english: 'Isaac', meaning: 'He will laugh', gender: 'male', nameType: 'hebrew' },
  { id: '103', hebrew: 'יעקב', transliteration: 'Yaakov', english: 'Jacob', meaning: 'Supplanter', gender: 'male', nameType: 'hebrew' },
  { id: '104', hebrew: 'יהודה', transliteration: 'Yehuda', english: 'Judah', meaning: 'Praised', gender: 'male', nameType: 'hebrew' },
  { id: '105', hebrew: 'יוסף', transliteration: 'Yosef', english: 'Joseph', meaning: 'God increases', gender: 'male', nameType: 'hebrew' },
  { id: '106', hebrew: 'משה', transliteration: 'Moshe', english: 'Moses', meaning: 'Drawn out', gender: 'male', nameType: 'hebrew' },
  { id: '107', hebrew: 'דוד', transliteration: 'David', english: 'David', meaning: 'Beloved', gender: 'male', nameType: 'hebrew' },
  { id: '108', hebrew: 'שלמה', transliteration: 'Shlomo', english: 'Solomon', meaning: 'Peaceful', gender: 'male', nameType: 'hebrew' },
  { id: '109', hebrew: 'אליהו', transliteration: 'Eliyahu', english: 'Elijah', meaning: 'My God is Yah', gender: 'male', nameType: 'hebrew' },
  { id: '110', hebrew: 'אלישע', transliteration: 'Elisha', english: 'Elisha', meaning: 'God is salvation', gender: 'male', nameType: 'hebrew' },
  { id: '111', hebrew: 'יחזקאל', transliteration: 'Yechezkel', english: 'Ezekiel', meaning: 'God strengthens', gender: 'male', nameType: 'hebrew' },
  { id: '112', hebrew: 'ירמיה', transliteration: 'Yirmiya', english: 'Jeremiah', meaning: 'God will exalt', gender: 'male', nameType: 'hebrew' },
  { id: '113', hebrew: 'ישעיה', transliteration: 'Yeshaya', english: 'Isaiah', meaning: 'God is salvation', gender: 'male', nameType: 'hebrew' },
  { id: '114', hebrew: 'שמואל', transliteration: 'Shmuel', english: 'Samuel', meaning: 'God has heard', gender: 'male', nameType: 'hebrew' },
  { id: '115', hebrew: 'בנימין', transliteration: 'Binyamin', english: 'Benjamin', meaning: 'Son of the right hand', gender: 'male', nameType: 'hebrew' },
  { id: '116', hebrew: 'רובן', transliteration: 'Reuven', english: 'Reuben', meaning: 'Behold a son', gender: 'male', nameType: 'hebrew' },
  { id: '117', hebrew: 'שמעון', transliteration: 'Shimon', english: 'Simeon', meaning: 'He has heard', gender: 'male', nameType: 'hebrew' },
  { id: '118', hebrew: 'לוי', transliteration: 'Levi', english: 'Levi', meaning: 'Joined', gender: 'male', nameType: 'hebrew' },
  { id: '119', hebrew: 'יששכר', transliteration: 'Yisaschar', english: 'Issachar', meaning: 'He has hired', gender: 'male', nameType: 'hebrew' },
  { id: '120', hebrew: 'זבולון', transliteration: 'Zevulun', english: 'Zebulun', meaning: 'Dwelling place', gender: 'male', nameType: 'hebrew' },
  { id: '121', hebrew: 'דן', transliteration: 'Dan', english: 'Dan', meaning: 'Judge', gender: 'male', nameType: 'hebrew' },
  { id: '122', hebrew: 'נפתלי', transliteration: 'Naftali', english: 'Naphtali', meaning: 'My struggle', gender: 'male', nameType: 'hebrew' },
  { id: '123', hebrew: 'גד', transliteration: 'Gad', english: 'Gad', meaning: 'Fortune', gender: 'male', nameType: 'hebrew' },
  { id: '124', hebrew: 'אשר', transliteration: 'Asher', english: 'Asher', meaning: 'Happy', gender: 'male', nameType: 'hebrew' },
  { id: '125', hebrew: 'אפרים', transliteration: 'Ephraim', english: 'Ephraim', meaning: 'Fruitful', gender: 'male', nameType: 'hebrew' },
  { id: '126', hebrew: 'מנשה', transliteration: 'Menashe', english: 'Manasseh', meaning: 'Making forget', gender: 'male', nameType: 'hebrew' },
  { id: '127', hebrew: 'מלאכי', transliteration: 'Malachi', english: 'Malachi', meaning: 'My messenger', gender: 'male', nameType: 'hebrew' },
  { id: '128', hebrew: 'הושע', transliteration: 'Hosea', english: 'Hosea', meaning: 'Salvation', gender: 'male', nameType: 'hebrew' },
  { id: '129', hebrew: 'יוחנן', transliteration: 'Yochanan', english: 'John', meaning: 'God is gracious', gender: 'male', nameType: 'hebrew' },
  { id: '130', hebrew: 'מתתיהו', transliteration: 'Matityahu', english: 'Matthew', meaning: 'Gift of God', gender: 'male', nameType: 'hebrew' },
  { id: '131', hebrew: 'נחום', transliteration: 'Nachum', english: 'Nahum', meaning: 'Comfort', gender: 'male', nameType: 'hebrew' },
  { id: '132', hebrew: 'חביקוק', transliteration: 'Chavakuk', english: 'Habakkuk', meaning: 'Embrace', gender: 'male', nameType: 'hebrew' },
  { id: '133', hebrew: 'צפניה', transliteration: 'Tzfanya', english: 'Zephaniah', meaning: 'Hidden by God', gender: 'male', nameType: 'hebrew' },
  { id: '134', hebrew: 'חגי', transliteration: 'Chagai', english: 'Haggai', meaning: 'My festival', gender: 'male', nameType: 'hebrew' },
  { id: '135', hebrew: 'זכריה', transliteration: 'Zecharya', english: 'Zechariah', meaning: 'God remembers', gender: 'male', nameType: 'hebrew' },
  { id: '136', hebrew: 'שרה', transliteration: 'Sara', english: 'Sarah', meaning: 'Princess', gender: 'female', nameType: 'hebrew' },
  { id: '137', hebrew: 'רבקה', transliteration: 'Rivka', english: 'Rebecca', meaning: 'To tie', gender: 'female', nameType: 'hebrew' },
  { id: '138', hebrew: 'לאה', transliteration: 'Leah', english: 'Leah', meaning: 'Weary', gender: 'female', nameType: 'hebrew' },
  { id: '139', hebrew: 'רחל', transliteration: 'Rachel', english: 'Rachel', meaning: 'Ewe', gender: 'female', nameType: 'hebrew' },
  { id: '140', hebrew: 'מרים', transliteration: 'Miriam', english: 'Miriam', meaning: 'Bitter sea', gender: 'female', nameType: 'hebrew' },
  { id: '141', hebrew: 'דבורה', transliteration: 'Devora', english: 'Deborah', meaning: 'Bee', gender: 'female', nameType: 'hebrew' },
  { id: '142', hebrew: 'רוט', transliteration: 'Rut', english: 'Ruth', meaning: 'Friend, companion', gender: 'female', nameType: 'hebrew' },
  { id: '143', hebrew: 'אסתר', transliteration: 'Esther', english: 'Esther', meaning: 'Star', gender: 'female', nameType: 'hebrew' },
  { id: '144', hebrew: 'חנה', transliteration: 'Chana', english: 'Hannah', meaning: 'Grace', gender: 'female', nameType: 'hebrew' },
  { id: '145', hebrew: 'יהודית', transliteration: 'Yehudit', english: 'Judith', meaning: 'Woman of Judea', gender: 'female', nameType: 'hebrew' },
  { id: '146', hebrew: 'תמר', transliteration: 'Tamar', english: 'Tamar', meaning: 'Date Palm', gender: 'female', nameType: 'hebrew' },
  { id: '147', hebrew: 'דינה', transliteration: 'Dina', english: 'Dinah', meaning: 'Judged', gender: 'female', nameType: 'hebrew' },
  { id: '148', hebrew: 'בתשבע', transliteration: 'Bat Sheva', english: 'Bathsheba', meaning: 'Daughter of oath', gender: 'female', nameType: 'hebrew' },
  { id: '149', hebrew: 'מיכל', transliteration: 'Michal', english: 'Michal', meaning: 'Who is like God', gender: 'female', nameType: 'hebrew' },
  { id: '150', hebrew: 'אביגיל', transliteration: 'Avigayil', english: 'Abigail', meaning: 'My father is joy', gender: 'female', nameType: 'hebrew' },
  { id: '151', hebrew: 'נועמי', transliteration: 'Noami', english: 'Naomi', meaning: 'Pleasantness', gender: 'female', nameType: 'hebrew' },
  { id: '152', hebrew: 'עפרה', transliteration: 'Ofra', english: 'Ophrah', meaning: 'Fawn', gender: 'female', nameType: 'hebrew' },
  { id: '153', hebrew: 'שושנה', transliteration: 'Shushana', english: 'Susanna', meaning: 'Lily', gender: 'female', nameType: 'hebrew' },
  { id: '154', hebrew: 'חולדה', transliteration: 'Chuld', english: 'Huldah', meaning: 'Weasel', gender: 'female', nameType: 'hebrew' },
  { id: '155', hebrew: 'איתא', transliteration: 'Ita', english: 'Ita', meaning: 'Belonging to', gender: 'female', nameType: 'hebrew' },
  { id: '156', hebrew: 'מלכה', transliteration: 'Malka', english: 'Milcah', meaning: 'Queen', gender: 'female', nameType: 'hebrew' },
  { id: '157', hebrew: 'נועה', transliteration: 'Noa', english: 'Noah', meaning: 'Motion', gender: 'female', nameType: 'hebrew' },
  { id: '158', hebrew: 'תרצה', transliteration: 'Tirtza', english: 'Tirzah', meaning: 'Pleasantness', gender: 'female', nameType: 'hebrew' },
  { id: '159', hebrew: 'גומר', transliteration: 'Gomer', english: 'Gomer', meaning: 'Completion', gender: 'female', nameType: 'hebrew' },
  { id: '160', hebrew: 'זפורה', transliteration: 'Tzippora', english: 'Zipporah', meaning: 'Little bird', gender: 'female', nameType: 'hebrew' },
  { id: '161', hebrew: 'אתי', transliteration: 'Adi', english: 'Adi', meaning: 'My ornament', gender: 'female', nameType: 'hebrew' },
  { id: '162', hebrew: 'עדית', transliteration: 'Aditi', english: 'Aditi', meaning: 'My witness', gender: 'female', nameType: 'hebrew' },
  { id: '163', hebrew: 'שירה', transliteration: 'Shira', english: 'Shira', meaning: 'Song', gender: 'female', nameType: 'hebrew' },
  { id: '164', hebrew: 'טליה', transliteration: 'Talia', english: 'Talia', meaning: 'Dew from God', gender: 'female', nameType: 'hebrew' },
  { id: '165', hebrew: 'אורית', transliteration: 'Orit', english: 'Orit', meaning: 'My light', gender: 'female', nameType: 'hebrew' },
  { id: '166', hebrew: 'אורלי', transliteration: 'Orli', english: 'Orli', meaning: 'Light is mine', gender: 'female', nameType: 'hebrew' },
  { id: '167', hebrew: 'מיה', transliteration: 'Maya', english: 'Maya', meaning: 'Water', gender: 'female', nameType: 'hebrew' },
  { id: '168', hebrew: 'גילה', transliteration: 'Gila', english: 'Gila', meaning: 'Joy', gender: 'female', nameType: 'hebrew' },
  { id: '169', hebrew: 'אמנה', transliteration: 'Emuna', english: 'Emunah', meaning: 'Faith', gender: 'female', nameType: 'hebrew' },
  { id: '170', hebrew: 'חיה', transliteration: 'Chaya', english: 'Chaya', meaning: 'Living', gender: 'female', nameType: 'hebrew' },
  { id: '171', hebrew: 'בתיה', transliteration: 'Bati', english: 'Bitya', meaning: 'Daughter of God', gender: 'female', nameType: 'hebrew' },
  { id: '172', hebrew: 'יונה', transliteration: 'Yona', english: 'Yona', meaning: 'Dove', gender: 'male', nameType: 'hebrew' },
  { id: '173', hebrew: 'אריאל', transliteration: 'Ariel', english: 'Ariel', meaning: 'Lion of God', gender: 'neutral', nameType: 'hebrew' },
  { id: '174', hebrew: 'אורי', transliteration: 'Uri', english: 'Uri', meaning: 'My light', gender: 'male', nameType: 'hebrew' },
  { id: '175', hebrew: 'נועם', transliteration: 'Noam', english: 'Noam', meaning: 'Pleasantness', gender: 'male', nameType: 'hebrew' },
];
